### ISSUE TITLE
Options for Load balancing SQL read/write splitting master slave queries

### ISSUE THREAD

**Issue by drgarciafuentes** [zalando/patroni#1049]
Hello,

I have a working Patroni/PostgreSQL bare metal cluster. We thought about implementing load balancing with HAproxy and would like to know which are the available options to split read/write queries in a master slave streaming replication scenario.
I've noticed a couple of conversations about the subject (#685, #766 and #828) but the discussing does not develop enough for us to take a specific route with confidence.
I'm aware of Spilo and Postgres-Operator but their design seems very container oriented which is not our situation.

Any guidance or leads in the right direction would be much appreciated. @CyberDem0n do you have any special recommendation this time.
Thanks in advance.

**Comment by CyberDem0n** [comment]
It looks like that you are looking for some magic proxy which will parse SQL and depending on the type of queries send them to master or replicas.

As I already explained [here](https://github.com/zalando/patroni/issues/766#issuecomment-411152242), only the application knows whether a specific query could be executed on the replica and the application should also be prepared that query executed on the replica might return stale data.

**Comment by joyider** [comment]
@CyberDem0n I'm not sure what what you mean by magic proxy :) The question is very relevant and what he asks for can be achieved by using pgpool-II, with or without patroni

This feature is also implemented in Stolon, and it is exactly what you say it is a SQL Parser what redirects the query to the slave nodes if it is a RO operation (SELECT).

This feature would be a killer if it somehow cloud be implemented into patroni since using pgpool in combination with patroni is very complicated.

This might be tons of work, but "If there's a will, there's a way" :)

**Comment by jberkus** [comment]
@joyider pgPool2 doesn't actually work to split queries.  Yes, it advertises that feature, but if you spin up a pgPool2 cluster and do actual traffic monitoring on the LB, you'll discover that 80-90% of queries hit the master.  I haven't tested the Stolon LB, but I strongly suspect that it has the same problem.  In addition, the double-parsing of all queries results in substantial latency overhead (as in +50% to +100% latency).

Only the application knows if it's *about* to do a write, therefore only the application can decide what kind of connection it needs.  While one could theoretically implement some kind of LB based on looking at session characteristics, how useful would that be? I don't know of a single ORM that sets these accurately.

Closing as #wontfix.
