### ISSUE TITLE
How to notify patroni of a postgres password change?

### ISSUE THREAD

**Issue by preet** [zalando/patroni#1130]
If one of the passwords that patroni uses for postgres (superuser or replication users) is changed, what procedure do I use to notify patroni? Assume I have just changed the passwords in postgresql. I tried updating the settings yaml with the new passwords and then issuing:
`patronictl -c /opt/my/data/patroni/patroni.yml reload my_db_cluster --role=any --force`

I get the message `Reload request received for member ns_node_hostname and will be processed within 10 seconds`, and see the following in the logs

```
2019-08-01 14:24:40,505 INFO: No PostgreSQL configuration items changed, nothing to reload.
2019-08-01 14:24:40,506 INFO: Lock owner: my_node_hostname; I am my_node_hostname
2019-08-01 14:24:40,515 INFO: no action.  i am the leader with the lock
```
I assume 'nothing to reload' means I've done something wrong. If not, is there a way I can verify patroni has updated its postgres credentials?

**Comment by CyberDem0n** [comment]
You did everything right.
`No PostgreSQL configuration items changed, nothing to reload.` that sentence applies to postgres parameters. Since no parameters changed there if no need to call `pg_ctl reload`.

But from this moment Patroni will use different credentials in order to connect to postgres and/or for replication.

**Comment by preet** [comment]
Thanks for confirming!
