### ISSUE TITLE
Liveness probe on k8s sts?

### ISSUE THREAD

**Issue by bappr** [zalando/patroni#1159]
Hey guys,

Any reason why you are not using Liveness/Readiness probes in your k8s statefulset (in this repo and in your helm chart)?
Can I use one? Wondering if it's gonna impact something else.

Thanks a lot,

Ben

**Comment by CyberDem0n** [comment]
Hi,

there is no big value in readiness probe. Patroni will not set role label until postgres is ready to accept connections.

With liveness probe it is a very interesting question. From one side we can use it as a sort of watchdog in order to protect from the case when Patroni crashed or become unresponsive, but from another side killing the stateful application is not always something that you want.

From the Patroni side it will require some little changes in order to implement the liveness probe. One should implement `do_GET_healthz()` method which always responds with http status code 200 in the `RestApiHandler` class.

**Comment by bappr** [comment]
Ok thanks for the info. ;)

**Comment by anikin-aa** [comment]
May be it is worth to use something like this in liveness probe:
```
state=$(curl -XGET --silent http://$(hostname -i):8008/ | jq -r '.state | ascii_downcase'); 
if [ "$state" != "running" ];
then
	exit 1;
fi
```

**Comment by CyberDem0n** [comment]
Nope, liveness probe should never take into account state of the postgres.

**Comment by mreise** [comment]
I am looking for liveness and readiness probe, too. Could be an approach to determine a simple liveness probe on TCP 8008 (patroni admin port)? At readiness probe I would check if state is running and label role is set like mentioned above. It is tested with version 1.5.6...

**Comment by CyberDem0n** [comment]
I would recommend you to read about liveness probes: https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html

**Comment by bappr** [comment]
@CyberDem0n i see not reason to close this issue. This post u shared does not mention anything dangerous, just how to use liveness probe.

When I opens the issue the problem here was very simple, postgres  sometimes is down and the pod is still running. Is it resolved?

**Comment by CyberDem0n** [comment]
> postgres sometimes was down and the pod was still running

This is absolutely normal workflow:
* Patroni is could do pg_basebackup or something similar in order to (re)initialize the replica.
* Patroni could do pg_rewind, therefore postgres will not be running
* postgres might fail to start due to different issues

Killing the pod in all this cases will not improve situation, it will just make it harder to investigate what is going on.

Liveness probe is a big footgun, I don't want to open a pandora box by implementing it.

**Comment by mubn** [comment]
Without a liveness probe, no reliable automatic primary failover is possible. Kubernetes pods may break. This missing feature prevents us from using this software in production...

**Comment by CyberDem0n** [comment]
@mubn well, liveness/readiness probes endpoints were implemented a long time ago: https://github.com/zalando/patroni/commit/db8c634db3c1059c4ae4b48903ec44157f5db2ca

But, I will not change my mind:
- they are dangerous and you have to really know what you are doing before using them.
- Patroni perfectly works without probes and they are not required for automatic failover or to detect the absent primary.
