### ISSUE TITLE
How to stop master for manual failover to standby cluster leader?

### ISSUE THREAD

**Issue by Vanav** [zalando/patroni#1164]
I have two Patroni clusters: `Master cluster` and `Standby cluster`. I want to failover manually to `Standby cluster` for maintenance.

If I do:
1) change `Standby cluster` to new master, 
2) change `Master cluster` to new standby,

then `pg_rewind` is executed on old master, and it takes a lot of time. 

I want to stop or make read only `Master cluster` first:
1) stop or make read only `Master cluster`,
2) change `Standby cluster` to master, 
3) change `Master cluster` to new standby,

It seems that `pg_rewind` will not be needed and executed in this case?

How can I stop or make read only `Master cluster`?

**Comment by CyberDem0n** [comment]
Yeah, this is a very good question.

If you create `standby_cluster` section in the config (patronictl edit-config), the existing master will demote, but unfortunately it will do an immediate shutdown.

What will definitely work:
1. shutdown all replica nodes
2. shutdown the primary

At this moment cluster is stopped and there are certain guarantees that all data was streamed via live replication connections and all wal segments were archived.

At this point you can convert it to the standby cluster:
1. create `standby_cluster` in the config (you need to define host, port or restore_command there)
2. start the former master and wait until it starts reporting as a standby_leader
3. start replicas

**Comment by Vanav** [comment]
> If you create `standby_cluster` section in the config (patronictl edit-config), the existing master will demote, but unfortunately it will do an immediate shutdown.

If I create `standby_cluster ` on `Master cluster`, in this moment there will be two slaves of each other (circular). `Master cluster` will not accept writes, it is good, so `pg_rewind` will be not needed. But I'm not sure, if circular slaves will run normally for a brief time?

>     shutdown all replica nodes
>     shutdown the primary

How can I do this on `Master cluster`? Patroni doesn't have a `stop` command.

**Comment by CyberDem0n** [comment]
> Master cluster will not accept writes, it is good, so pg_rewind will be not needed

The problem is that after an immediate shutdown the standby cluster will be slightly behind the former master. This is exactly the case for pg_rewind.

> How can I do this on Master cluster? Patroni doesn't have a stop command.

You just need to stop Patroni and it will gracefully stop postgres.

**Comment by rodinasophie** [comment]
@CyberDem0n, sorry for resurrecting the old issue, I just wanted to be precise on quotation:

> What will definitely work:
> 
> shutdown all replica nodes
> shutdown the primary
> At this moment cluster is stopped and **there are certain guarantees** that all data was streamed via live replication connections and all wal segments were archived.

I'm searching for the clean way to stop patroni cluster such that the promotion of any node to the leader on next cluster start doesn't lead to data loss. I know that in general case it's impossible, because of replication lag, but let's suppose that the network is good enough and no replication lag exists.

I think that we can't guarantee that after all replicas are stopped, the master didn't accept at least one record and this record is not wiped away by the `pg_rewind` procedure if some of the previous replicas were elected as the leader on cluster start.

Is there a way to stop the patroni cluster and be sure that in case of **reliable network**, we assuredly stop the cluster with the same copy of data on each node?

**Comment by CyberDem0n** [comment]
@rodinasophie there are two different cases:
1. the standby cluster is streaming from the primary (it is up to you to make sure that it is)
2. the standby cluster is replaying WAL segments from the archive.

There is also a combination of two above, which would be the best case scenario.

During graceful stop of Postgres primary it does the following:
1. stops accepting new connections and closes any existing client connections (replication connections are not terminated)
2. writes all dirty pages from shared buffers do disk
3. writes shutdown checkpoint record to WAL (if archiving is enabled it switches a WAL file and writes it to the new file)
4. updates `pg_control`, with the latest shutdown checkpoint LSN
5. waits until all replication connection received and acknowledged WAL up to shutdown checkpoint LSN
6. archives all WAL segments (if archiving is enabled, the last WAL segment that contains only shutdown checkpoint record is not archived)

5 - guarantees that there will be no data loss on standby nodes that were streaming during the shutdown
6 - guarantees that backup + WAL will allow to restore everything up to the moment when primary was stopped

Before promoting standby cluster you may verify that it received/replayed everything up to shutdown checkpoint LSN.

There is one little quirk though - if the standby node was replying WAL files from the archive, but not streaming, it will be ~40 bytes behind the old primary. That is, it will not replay WAL segment with shutdown checkpoint record, because it is not archived by postgres (see 3). Such situation will require pg_rewind on the old primary to resolve, but, there is no data loss.

**Comment by rodinasophie** [comment]
@CyberDem0n, thank you very much for such a detailed answer!
