### ISSUE TITLE
patronictl smoke tests

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#1213]
I recently noticed that the current Debian packages broke `patronictl` because `python3-distutils` wasn't a dependency, but for whatever reason is required.

So I think it would be useful to exercise `patronictl` in at least some minimal way during either the regression or behave tests (or add yet another test suite for it), as it is a pretty major part of patroni from an end-user/admin point-of-view.

**Comment by CyberDem0n** [comment]
Hi @mbanck, yes that unfortunate :(

There are actually unit and behave tests for patronictl and they are not failing because I assume that during the package build python3-distutils is installed.

The problem was introduced [here](https://github.com/zalando/patroni/commit/78999a2d621397381b914ede5f26f328e7a7930d), and in https://github.com/zalando/patroni/commit/0a1d9b0a251b70df7eb4b4004c86e169cddd8ed1 I fixed it. Basically the master branch does not depend on distutils anymore.

**Comment by mbanck** [comment]
Ok, then maybe it is rather a problem with the Debian packaging, which is checking (I think) `.egg-info/requirements.txt` for which packages to Depend on it - could be that run-time imports in the `patronictl` script aren't included there?

**Comment by mbanck** [comment]
I'm closing this as unit/behave tests are present and this should count for smoke tests; the issue I saw was something outside the scope of patronictl smoke tests
