### ISSUE TITLE
Permanent physical slots on all nodes

### ISSUE THREAD

**Issue by perwigren** [zalando/patroni#1233]
Currently, if I specify some permanent physical slots in Patroni, they will only exist on the master. We would like to do cascaded streaming from replicas instead of the master, for example to avoid putting load on the master during `pg_basebackup`.

How about creating the permanent slots on all nodes, then regularly call `pg_replication_slot_advance()` (pg11+) to forward the older ones to the newest restart_lsn of the slots?

**Comment by CyberDem0n** [comment]
What problem exactly are you trying to solve?
Patroni can bootstrap a new replica not only from the master, but also from any other cluster member which has `tags.clonefrom: true`.

If you are talking about the standby_cluster, imho it would be much easier to not specify slot at all and rely on wal archiving. It is also possible to change the `standby_cluster` config on the fly.
I.e. first put there host:port of the replica and later, when it is already up and running, change them to master.

**Comment by perwigren** [comment]
We have on-site Patroni clusters of three nodes in three different data centers. We want to point Barman's pg_receivewal and pg_basebackup to the PG nodes in the same data center as the backup servers to avoid extra and bursty cross-data center network traffic or to avoid extra load on the master. Also, sometimes for various reasons we need extra replicas and/or pg_receivewals not controlled by Patroni. The master is not always the best node to stream from.

**Comment by oleg9301** [comment]
> Barman's pg_receivewal and pg_basebackup to the PG nodes in the same data center as the backup servers

Can Barman do streaming backup from standby/slave mode?
As I undestande from http://docs.pgbarman.org/release/2.9/#concurrent_backup_and_backup_from_a_standby, it can't be done with  pg_basebackup.

**Comment by oleg9301** [comment]
This would be a good feature, I have some clusters, where standby do nothing, and master do everyhing(write/read/backup). It would be good, to do streaming backup from standby.

**Comment by CyberDem0n** [comment]
Well, let's imagine that we create a permanent slot on all nodes, and there are no processes streaming from them. Or maybe there is just one process which is streaming from one node, or two processes are streaming from two nodes. In any case, there might be some nodes where the replication slot holds the WAL files from being cleaned up due to the no receiver process.
You suggest using `pg_replication_slot_advance()` to mitigate the problem. But what if on the given node usually there is a process that receives the stream, but now it is temporary down? That would break all promises and not using replication slots at all will work absolutely the same.
