### ISSUE TITLE
Point in time recovery using Patroni

### ISSUE THREAD

**Issue by gowtham500** [zalando/patroni#1309]
Hello team,

Thanks for this awesome tool and all the good stuff.

 My understanding from documentation is that I can do point in time recovery using pgbackrest with custom_bootstrap method.  I have setup patroni (3 nodes) with pgbackrest and consul. I used below script.

## custom bootstrap ##
bootstrap:
  method: pgbackrest
  pgbackrest:
      command: /etc/patroni/bootstrap.sh
      keep_existing_recovery_conf: False
      recovery_conf:
            recovery_target: immediate
            recovery_target_action: promote
            restore_command: /bin/pgbackrest --stanza=pgadmin archive-get %f %p

And used below script to do create replica.

## custom create replica ##
postgresql:
    create_replica_methods:
        - pgbackrest
    pgbackrest:
        command: /etc/patroni/bootstrap.sh
        keep_data: True
        keep_existing_recovery_conf: True
        no_params: false

## /etc/patroni/bootstrap.sh ##

/bin/pgbackrest --stanza=pgadmin --delta restore --set=20191127-153046F_20191127-154126I --log-level-console=info

with above setup, this is how I start to do PITR.

1. Stop patroni on all nodes.
2. Wipe data directory on all nodes - rm -rf /app/pgsql/12/data.
3. Start patroni on all nodes.
4. This simulates a race condition.
5. Remove initialize key from consul.
6. Patroni chooses a leader and starts to bootstrap it from above script.
7. Once the leader is boostrapped, patroni calls create-replica method for all the slave nodes.
8. The entire cluster is back online successfully to the backup set which I have provided in boostrap.sh

## My doubts: ##

1. Are there any other ways to do PITR without bootstrapping.
2. In above scenario i am forced to do bootstrap from scratch inorder to do PITR and unable to make use of --delta restore option of pgbackrest for custom_bootstrap.
3. Is my understanding correct here?

**Comment by CyberDem0n** [comment]
> Are there any other ways to do PITR without bootstrapping.

Yes, but it is a bit hacky.
Stop all nodes. On one of the nodes define the custom replica creation method with `recovery_target_time` and `recovrery_target_action`, remove pgdata and start patroni.
After that you should not forget to change the custom replica creation method back.

> In above scenario i am forced to do bootstrap from scratch inorder to do PITR and unable to make use of --delta restore option of pgbackrest for custom_bootstrap.

Yes, Patroni will not start the bootstrap process if PGDATA is not empty.
There is a workaround though. You can rename it and later in the bootstrap script rename it back

**Comment by deepd** [comment]
Will the following work:

1. Stop the nodes running the replicas
2. Stop patroni service on the node (say n1) running the leader
3. Stop postgres on n1
4. Do PITR using a command like `pgbackrest --stanza=app --log-level-console=info --delta --type=time --target="2021-02-11 06:47:32" --target-action=promote restore`
5. Start postgres on n1
6. Start the patroni service on n1. This may lead to the leader being demoted to a replica because of patroni's internal logic as in [here](https://github.com/zalando/patroni/blob/v1.6.5/patroni/ha.py#L934) and [here](https://github.com/zalando/patroni/blob/fe23d1f2d06271a374972e6f5e99de5d947f1c66/patroni/ha.py#L617).
7. Monitor for a few loops to see if n1 is not the leader. If n1 loses leadership, put patroni in maintenance mode and failover to n1. Patroni [makes sure](https://github.com/zalando/patroni/blob/v1.6.5/patroni/ha.py#L934) n1 is leader now. Remove patroni from maintenance mode.
8. Bring up the other nodes hosting replicas and reinitialize the replicas using patroni.

**Comment by dhavalshukla00** [comment]
I am also trying to achieve same thing.

Following the below :

1. Stop patroni on all nodes.
2. Doing the Point in time recovery using delta restore on primary.
3. Start patroni on primary node.
4. I see the full database is restored and PITR does not work.

But when I follow the bootstrap method for point in time recovery it works.

So as per all the comments here, does that mean that PITR does not work with delta restores?
