### ISSUE TITLE
does WAL archive have to be on shared storage?

### ISSUE THREAD

**Issue by jankeirse** [zalando/patroni#140]
More a question than an Issue: I would like to know if the WAL archive defined in the archive_command has to be accessible to the slave nodes. Is this supposed to be an NFS share that all nodes can access or can it be local storage that is not accessible from the slaves except through Postgres?

**Comment by jankeirse** [comment]
Yes it needs to be shared, I tried without and it doesn't work.

**Comment by alexeyklyukin** [comment]
@jankeirse yes, it should be accessible to the replicas to read as well as to the master to write (and since each replica may become a master at some point, in reality it should be r/w for all nodes). If you want the purely postures-based solution - use streaming replication in 9.4+ together with replication slots.
