### ISSUE TITLE
3 nodes patroni with 3 etcd on same node.

### ISSUE THREAD

**Issue by amadhaka** [zalando/patroni#1435]
Dear Team,
I am running a 3 node patroni on 3 different zones in google cloud and running etcd on the same nodes, will this be fine for prod setup as well instead of going with a separate 3 node etcd cluster ?
i assume if patroni node goes down etcd will be down as well and the remaining node will become master as 2 alive patroni nodes will be pinging to 2 remaining etcd running on these same nodes ?
please suggest pros and cons of hosting etcd on same node as patroni for a 3 node cluster.
Thanks,
Aman

**Comment by smirnov-mi** [comment]
I tried to run such setup but failed as etcd cluster didn't work well. It crashed every time one node went down, and wasn't able to rebuild itself. They say it's an etcd issue, I wasn't able to fix it, or configure it properly.

**Comment by amadhaka** [comment]
Thanks so you used consul or zookeeper instead ?

**Comment by smirnov-mi** [comment]
I‘m using kubernetes‘s etcd

**Comment by vitabaks** [comment]
@amadhaka 
You should familiarize yourself with the etcd [documentation](https://etcd.io/docs/v3.3.13/op-guide/). 
And when you are sure that you understand how it works, you can make your decision.
I install etcd in production on the same servers as PostgreSQL ( see my [scheme](https://github.com/vitabaks/postgresql_cluster) ), but only because I know what I'm doing!

Avoid storing etcd data on the same drive along with other processes (such as the database) that are intensively using the resources of the disk subsystem! Store the etcd and postgresql data on different disks (ETCD_DATA_DIR), and use ssd drives if possible.

In the cloud, everything may not be so stable, since you do not control the infrastructure.
I would also recommend to increase the parameter values ​​(example):
ETCD_ELECTION_TIMEOUT = "5000"
ETCD_HEARTBEAT_INTERVAL = "1000"

But, it may be better if you can afford a dedicated cluster etcd (three nodes, but five nodes are better) that you will use for all your PostgreSQL (Patroni) clusters.

**Comment by amadhaka** [comment]
@vitabiks, thanks a lot for such an informative reply , etcd I understood fine and it will going to act as dcs for me I am taking 3 nodes on 3 different zones while my postgre/patroni is in 2 zones as 2 nodes in 1 and 1 node in another as demand from client is to have synchronous replication so less spawning on zones is better for me and also etcd on same host is bit uncomfortable due to its own load although very minimal, instead of HA proxy I took cloud TCP load balancer , I am doing integration testing with application as they are saying they do have connection pooling and handling mechanism within the application so pgbbouncer is on hold as of now ,if all goes well I will prepare and share the document with all of us.
thanks again for help, appreciate it.

**Comment by KaremSalhi** [comment]
Hi, I need to run  3 node patroni on 3 different centos7 server  and run 3 etcd on the same nodes.
I need your support
