### ISSUE TITLE
Tablespace errors/questions

### ISSUE THREAD

**Issue by dalton007-1** [zalando/patroni#1469]
I'm testing tablespaces, and I think from my research I'm going to need to use a script to clear the tablespace then call pg_basebackup. I'm looking for some example scripts, advice, what are other people doing. I've been running a patroni cluster for several months and have some experience creating pre/post backup scripts in barman.  I've attached more detailed information/patroni log file entries.
[post_tablespace_issue.txt](https://github.com/zalando/patroni/files/4393814/post_tablespace_issue.txt)

**Comment by CyberDem0n** [comment]
> Mar 27 13:16:31 afes01pgis01 patroni[1342]: 2020-03-27 13:16:31,315 INFO: running pg_rewind from afes01pgis02
Mar 27 13:16:31 afes01pgis01 patroni[1342]: 2020-03-27 13:16:31,336 ERROR: Exception when working with leader
Mar 27 13:16:31 afes01pgis01 patroni[1342]: Traceback (most recent call last):
Mar 27 13:16:31 afes01pgis01 patroni[1342]:   File ""/usr/local/lib/python3.6/dist-packages/patroni/postgresql/rewind.py"", line 55, in check_leader_is_not_in_recovery
Mar 27 13:16:31 afes01pgis01 patroni[1342]:     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **kwargs) as cur:
Mar 27 13:16:31 afes01pgis01 patroni[1342]:   File ""/usr/lib/python3.6/contextlib.py"", line 81, in __enter__
Mar 27 13:16:31 afes01pgis01 patroni[1342]:     return next(self.gen)
Mar 27 13:16:31 afes01pgis01 patroni[1342]:   File ""/usr/local/lib/python3.6/dist-packages/patroni/postgresql/connection.py"", line 43, in get_connection_cursor
Mar 27 13:16:31 afes01pgis01 patroni[1342]:     with psycopg2.connect(**kwargs) as conn:
Mar 27 13:16:31 afes01pgis01 patroni[1342]:   File ""/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py"", line 126, in connect
Mar 27 13:16:31 afes01pgis01 patroni[1342]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Mar 27 13:16:31 afes01pgis01 patroni[1342]: psycopg2.OperationalError: FATAL:  password authentication failed for user ""postgres""
Mar 27 13:16:31 afes01pgis01 patroni[1342]: FATAL:  password authentication failed for user ""postgres"""
..........
NOTE:I have verfied that I can psql into postgresql on each member, user postgres, with the same password, when patroni/postgresql is running properly.  

pg_rewind requires either superuser of postgres11 and a special setup.
In your case Patroni clearly tried to execute pg_rewind and failed because external superuser connection isn't allowed.

Regarding reinit and pre/post backups scripts. There is no such mechanism in Patroni, but you can write your own replica creation scripts. More details you can find in the [documentation](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas). Basically you just need to write a script-wrapper and configure patroni to execute it instead of pg_basebackup.

**Comment by dalton007-1** [comment]
Ok I believe I understand re: doing a failover/reinit. I've read the documentation & I'll work on creating a script. If there are any examples/similar you can point me toward it would be much appreciated.

I've further diagnosed the postgres issue base on your feedback. I believe I have verified that user postgres is a postgresql superuser. I have also included my show_config, perhaps I have misconfigured something there...thanks for your help.

[show_config.txt](https://github.com/zalando/patroni/files/4395785/show_config.txt)
[postgres super user check.txt](https://github.com/zalando/patroni/files/4395786/postgres.super.user.check.txt)

**Comment by CyberDem0n** [comment]
Of course the postgres user is superuser in your case, but it also must be allowed to login remotely.
Since you are on postgres 11, you can also [create a special user](https://www.postgresql.org/docs/current/app-pgrewind.html#id-1.9.5.9.8) for pg_rewind and add its credentials into `postgresql.authentication.rewind`.

Regarding the replica creation script, you can take https://github.com/zalando/patroni/blob/master/patroni/scripts/wale_restore.py as an example.

**Comment by dalton007-1** [comment]
Thanks for your help, I'll attempt to address the issues with these guidelines.
