### ISSUE TITLE
Queries..

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#1512]
Patroni is a great project, Thanks for the great work.

I have a few questions that I could not find in the documentation.

1. In an active+standby site (each site is multi-node i.e. master+few replicas), if master on active is re-selected, how standby comes to know of the new active-master? (Do I need to reconfigure YAML, and reload?)

2. Is there a config param to provide dbname (such as $POSTGRES_DB that postgres docker has) to bootstrap with it (and use 'postgres' as default). I understand that I can do custom bootstrap .. but want to explore first if there is a config for it (could not find in documentation).

3. For testing purposes, I have to constantly deploy and redeploy and end up with ZK node and no DB directory, that I delete using patronictl remove <cluster>, and challenge text( Yes I am aware). Is there a REST equivalent (w/o challenge)

Thanks,

**Comment by CyberDem0n** [comment]
1. There is no indicator in the yaml file about the current role. Cluster topology (and leader) is discovered from DCS.
2. No. Initdb always creates postgres database by default.
3. It is asking to confirm because the operation is unsafe, there is no such REST API endpoint and will never be. If you know what you are doing you can automate it by piping the answer to patronictl or connect to zookeeper and remove znodes from there.

**Comment by sandeepkalra** [comment]
Thanks. On question#1. Are we assuming the same DCS for the 2 sites?

**Comment by CyberDem0n** [comment]
If you are talking about the [standby cluster](https://patroni.readthedocs.io/en/latest/replica_bootstrap.html#standby-cluster) feature, you should provide the single endpoint (HAProxy, or update DNS after failover) which always connects to the current primary.

In case if there is no such possibility you can always update the `standby_cluster` section to point it to the new primary:
```
patronictl edit-config
```

**Comment by sandeepkalra** [comment]
Thanks. That clarifies it for me.
