### ISSUE TITLE
Add on_before_stop callback

### ISSUE THREAD

**Issue by eugene-chernyshenko** [zalando/patroni#1517]
Is it possible to add on_before_stop callback?

**Comment by CyberDem0n** [comment]
How could it be useful?
Also callbacks are asynchronous, but before stop can't be like this, so it would delay the shutdown.

**Comment by eugene-chernyshenko** [comment]
For example, it could be useful if you use CDC debezium connector to your master. You should stop the connector before stopping the master.

**Comment by eugene-chernyshenko** [comment]
Even asynchronous call may be helpful than nothing

**Comment by eugene-chernyshenko** [comment]
https://issues.redhat.com/browse/DBZ-1727

**Comment by CyberDem0n** [comment]
Usually we stop postgres in order to perform a switchover. If you stop a logical receiver _before_ postgres shutdown, it will miss some events, because there is no mechanism in postgres to "replicate" replication slots. Logical slots could be created only on the primary.

The problem you are trying to solve is not in Patroni or PostgreSQL, but in Debezium, because it doesn't properly implement logical replication protocol.

**Comment by avinashvallarapu** [comment]
@eugene-chernyshenko I hope this issue, if fixed, could solve your problem (which if of course not with Patroni but with PostgreSQL). 
https://github.com/zalando/patroni/issues/1567
Patroni should not stop a newly elected leader before performing a promote which is how it should behave. 
However, we may request a callback which is wide open for several such scripted actions when somebody explicitly requires it.
