### ISSUE TITLE
Complete disaster recovery?

### ISSUE THREAD

**Issue by bodymindarts** [zalando/patroni#157]
We are trying to make patroni bring back a cluster from S3 in the event that everything goes down. For now we have implemented a work around that adds the initialization key and a fake leader entry to etcd to fool patroni into restoring from backup.

Are there considerations to support this kind of feature in patroni itself?

**Comment by alexeyklyukin** [comment]
Yes, the recently released 0.80 (https://github.com/zalando/patroni/releases/tag/v0.80) actually supports cloning the replicas with the replica creation method that does not require an active replication connection. 

You have to create the initialize key in etcd if it's not already there (otherwise, the node will attempt to initialize itself as a new master), and have **no_master: true** flag set for your replication method that should support running without the master connection. The version of the WAL-E script that comes with 0.80 already supports this. Of course, there needs to be a base backup and WAL files accessible to this replica creation method.

**Comment by drnic** [comment]
Ok thanks. I think thru trial and error we realized the need for the /initialize key to be pre-set. So we now backup sysid into the s3 /wal folder on start; then our startup script looks to preseed /initialize (if missing) from this backup if it's missing.

Will try out clonefrom. We just put in a wal-e restore command in it?

**Comment by drnic** [comment]
Sorry the clonefrom flag is unrelated.

**Comment by LappleApple** [comment]
@bodymindarts @drnic Hi guys, any updates here? Wondering if you have follow-up questions or if we can close out this issue.

**Comment by alexeyklyukin** [comment]
Patroni 1.1 has added a 'scaffold' command to patronictl in order to create initial structure in Etcd. While it does't allow you to create the permanent leader key, one should be able to avoid having it by using `nofailover` tags on all replicas. Need to actually check if it works.

**Comment by CyberDem0n** [comment]
Custom bootstrap covers it 100%: https://github.com/zalando/patroni/pull/454
