### ISSUE TITLE
Cannot bootstrap a cluster because of 5s session TTL, consul complains

### ISSUE THREAD

**Issue by victor-sudakov** [zalando/patroni#1579]
I'm trying to bootstrap a patroni cluster with consul, and keep getting the following error
WARNING: Retry got exception: 500 rpc error making call: Invalid Session TTL '5000000000', must be between [10s=24h0m0s]

This probably means that consul does not like patroni's session timeout which is 5 sec (?). However, for the life of me, I don't understand where this default 5s comes from, and how and where to set at least 10s in the Patroni config.

Attaching both log and config.

[log.txt](https://github.com/zalando/patroni/files/4744707/log.txt)
[12-test4.yml.txt](https://github.com/zalando/patroni/files/4744708/12-test4.yml.txt)

**Comment by CyberDem0n** [comment]
For some reason sessions in Consul expiring twice longer than requested, i.e. if you create the consul session with TTL=30s, it will be destroyed only after 60s, therefore Patroni divides the requested ttl by two.

Also it is not possible to create a session with TTL smaller than 10s by default, unless you changed it in the Consul configuration file.

From the logs it seems that you want to run Patroni with ttl=10. That's pretty terrible idea, it leaves absolutely no room for retries in case of minor issues and will increase chances of false positives. I wouldn't recommend to have ttl smaller that 20 and if you do so please change the loop_wait and retry_timeout accordingly, so `ttl <= loop_wait + 2*retry_timeout`.

**Comment by victor-sudakov** [comment]
Thanks for the reply. I was unable to find timing formulas in the official Patroni documentation (are there?). The example config in Debian gives "ttl: 30, loop_wait: 10, retry_timeout: 10" so I just divided each number by 3, because I a quicker failover  in a fast LAN environment.
 
If I want a quicker than default failover, will the following numbers do?   "ttl: 20, loop_wait: 3, retry_timeout: 9" ? I'm still guessing and would appreciate some recommendations.

And I'm going back to etcd.

**Comment by CyberDem0n** [comment]
> because I a quicker failover in a fast LAN environment.

Think about the case when the leader node is struggling under the high load and Patroni is not able to run HA loop fast enough. It will end up in the leader key expired.

> ttl: 20, loop_wait: 3, retry_timeout: 9"

Sorry, the equation was wrong. If you set ttl to 20, then either loop_wait should be 2 seconds (what is quite small), or you need to decrease retry_timeout to 8.

The idea behind, that if the leader fails to update the leader lock it should demote postgres faster than leader lock expires.

**Comment by victor-sudakov** [comment]
Which of the three parameters is the starting point of all calculations (from which other parameters should be derived)?

I tried a simple test where a shell script inserts 1 row and then sleeps 1 second, with default timings (ttl: 30, loop_wait: 10, retry_timeout: 10). Then I would halt the host running the leader, and count failed inserts. I counted 13-16  failed inserts before a new leader was elected. Just wondering if I can make Patroni react more quickly or if it is already the limit.

**Comment by victor-sudakov** [comment]
> If you set ttl to 20

It is not that I want to set the timings to some particular values. I want to achieve a quicker switchover than that with the default values. Can you please recommend them?

**Comment by CyberDem0n** [comment]
> I want to achieve a quicker switchover

Switchover or Failover? There is a difference!

**Comment by victor-sudakov** [comment]
> > I want to achieve a quicker switchover
> 
> Switchover or Failover? There is a difference!

Which one is in case of hardware failure or loss of connectivity? Failover it is, I think.

**Comment by CyberDem0n** [comment]
The `ttl` parameter is responsible for the speed of failover.
Other nodes will start the leader race when the leader key expired after the ttl.

As I already told, there is always a tradeoff between the speed of failover and false positives.
If you set the ttl to 10 seconds there will be very little room for error if the primary is under stress or in case of short network issue. Or in other words, by making the ttl too small you start decreasing availability.

**Comment by victor-sudakov** [comment]
I'm struggling to grasp the whole picture. How many times during the loop_wait period does the leader node try to touch the leader key?

Do you probably have a flowchart of the algorithm somewhere?

And don't you think this is not quite the right place for such a discussion? Is there a mailing list somewhere, or can I mail you directly?

**Comment by CyberDem0n** [comment]
There is no mailing list, only Slack channel, which doesn't keep the long history of messages. Regarding direct emails: IMO there is not much value in it, because I won't be able to poke other people at it.

There is a [flowchart](https://github.com/zalando/patroni/blob/master/docs/ha_loop_diagram.png), but it is a "bit" outdated.

There is also the [documentation](https://patroni.readthedocs.io/en/latest/SETTINGS.html):
* loop_wait: the maximum number of seconds the loop will sleep. Default value: 10
* ttl: the TTL to acquire the leader lock (in seconds). Think of it as the length of time before initiation of the automatic failover process. Default value: 30
* retry_timeout: timeout for DCS and PostgreSQL operation retries (in seconds). DCS or network issues shorter than this will not cause Patroni to demote the leader. Default value: 10

During HA loop:
1. **Every node** MUST fetch the cluster topology from DCS. It could take up to `retry_timeout` in worst case. If the leader isn't able to do it - postgres will be demoted.
2. **The leader** MUST update the leader key or session in DCS. It could take up to `retry_timeout` in worst case. I the leader isn't able to do it - postgres will be demoted.


Let assume parameters are default: ttl=30, loop_wait=10, retry_timeout=10 and node is the leader.

Now comes very simple math:
0: we updated the leader key
10: we slept for 10 seconds and woke up
20: we spent 10 seconds in order to fetch cluster topology from DCS and succeeded!
30: we spent yet another 10 seconds trying to update the leader key and failed!
30: the leader key expired and other nodes started the leader race.

That's why there is a requirement `ttl >= loop_wait + 2*retry_timeout`, or even better if it would be `ttl > loop_wait + 2*retry_timeout`

**Comment by victor-sudakov** [comment]
Wow! Thanks for the detailed explanation and the chart. I had thought that everything (updating the leader key, fetching cluster topology, the whole run cycle actually) happens within each iteration of the loop. Now I see it is not the case.

Then, why do we need non-zero loop_wait at all? It seems that if a node decides to sleep at the wrong moment, there can be a race condition.

**Comment by CyberDem0n** [comment]
> I had thought that everything (updating the leader key, fetching cluster topology, the whole run cycle actually) happens within each iteration of the loop. Now I see it is not the case.

It is the case. The loop consists of:
1. Fetch cluster
2. Update leader (on leader node)
3. Make sure that postgres in a good shape and do some action if it is not.
4. Update member key
5. Sleep until the next time to run 1

The sleep (5) on replicas is interrupted if the leader key disappeared from DCS.

Regarding setting the loop_wait to 0: what would it bring us except bombing the DCS and postgres with queries?

**Comment by victor-sudakov** [comment]
If a) sleeping time comes only after steps 1-4 are processed (I could not find sleep in the flowchart) and b) sleep on replicas is interrupted if the leader key disappears, then I agree, setting loop_wait to 0 makes no sense, and setting it non-zero may actually decrease load.

**Comment by victor-sudakov** [comment]
Should we close this issue?
