### ISSUE TITLE
Super User password on plain text

### ISSUE THREAD

**Issue by gabricar** [zalando/patroni#1584]
As far as I understand and tested it. the postgres super user password cannot be removed from the patroni yml file. I see this as a major security issue.

If that is the case can at least some encryption be implemented? Ideally a bcrypt Hash.

this way after the cluster deployment we can remove the bootstrap password and leave the postgres pwd encrypted. 

thx.

**Comment by SK-000** [comment]
@CyberDem0n  - 

Hi Alex , 

We are working on auto password  rotation for  postgres DB user  (superuser) ,  just want to under stand if we change the password does it will impact any replication or connectivity issue in between primary and replica.

Since we have mentioned that super user and replication user password explicitly in patroni yml file. 

Kindly share your insight on this. Thank you !
