### ISSUE TITLE
Slots-Setting unclear

### ISSUE THREAD

**Issue by mr-deamon** [zalando/patroni#1647]
Hi
I am trying to configure barman in order to have a streaming backup from the active PG-instance. I read about the slots:-configuration, but i honestly don't understand it well enough.
If i read this issue https://github.com/zalando/patroni/issues/1056 it sounds like slots can only be configured over the api once patroni has started (which actually works). But what for is the documentation of the yaml-file here https://patroni.readthedocs.io/en/latest/SETTINGS.html. If i set this, it neither creates a slot on start (which looks like normal) nor does it copy it after manually creating and switchover.

Sorry to ask this, but i'm honestly a bit lost :)

**Comment by CyberDem0n** [comment]
Hi, I think reading https://patroni.readthedocs.io/en/latest/dynamic_configuration.html should give more clarity.

Dynamic configuration is stored in DCS. The `slots` parameter is a part of dynamic configuration.
In order to simplify the process of deploying new clusters with custom dynamic configuration we invented `bootstrap.dcs`. It's content is written into DCS when the new cluster is being created (initdb or custom bootstrap).

**Comment by mr-deamon** [comment]
Thanks, that helped a lot! It is working now!
