### ISSUE TITLE
Version specifications in requirements.txt have lax constraints

### ISSUE THREAD

**Issue by aaliddell** [zalando/patroni#1707]
**Describe the bug**
The package versions of almost all dependencies in requirements.txt are either unconstrained (e.g. `PyYAML`) or are only constrained by a minimum version (e.g. `click>=4.1`). Many of these libraries could be locked at the major version level (as you have done with `python-etcd`), which would allow flexibility in package versions, but would not accept breaking changes expected of a major version increase. Some packages are already a number of major versions behind, meaning any version in that span would be considered valid by pip etc.

**Expected behavior**
The minimum viable versions of packages should be established, then upper bound constraints should set at either a major or minor version above.

**Comment by CyberDem0n** [comment]
I have a slightly different opinion on that.
Some of these modules already not maintained and didn't receive updates for a few years (python-etcd, python-consul, prettytable).

Interfaces of some other modules are very stable and our usage of them is very basic. Do you really think that `yaml.safe_load()` will ever change?

Locking the minimal version in some cases is required, because we know 100%  that older versions don't have some specific features we need.

Once being the maximum version set, someone should also maintain it, which requires additional time spent.
While now we get it for free, because all tests (unit and integration) are automatically using the [latest version](https://github.com/zalando/patroni/blob/master/.travis.yml#L132) of all dependencies.

Also, in most cases Patroni installed just to the system (without virtualenv and co), and too strict version pinning will increase dependency hell. 
Yes, I know that the new releases of some dependencies might break old versions of released Patroni pip packages, but in general we expect that people should be using the latest Patroni release.

Actually, on practice, most of the issues we have had so far, were from the `requests` module, which is not even directly included in requirements.txt and of course not used. The source of these issues were releases of a new version of the `urllib3`, but the `requests` has too strict requirement for the maximum version of urllib3.

Summary: maintaining min-max requires some work, but with very little (close to no) benefits not only for us, but also for end-users.
