### ISSUE TITLE
Pure raft or etcd3, what would you advise on production?

### ISSUE THREAD

**Issue by TonyGlob** [zalando/patroni#1723]
Hello.

I saw recommendations about etcd usage with patroni and understand about new bugs possibility in new feature. But there are no performance info about pure raft implementation. Maybe you can help me.

What performance hits has pure raft implementation? Does it good to use it on production or better use other options?

Best regards, Anton.

**Comment by CyberDem0n** [comment]
Postgres performance doesn't depend on DCS.

**Comment by TonyGlob** [comment]
Thanks for your reply. 
Yes, you are right, of course. 
I should have asked with more details.
There is recommendation that etcd app should be placed on different with postgresql servers because of great etcd io load. So does pure raft implementation has same great io impact, such it can decrease postgresql performance on heavy load if it placed on the same server? Or is pure raft load so insignificant that i can host both postgres and raft on the same server without any worry?

**Comment by luss** [comment]
I'm assuming that once the pure raft protocol is more battle tested it will
be the default choice to use unless you perhaps are already running an etcd
(or patroni or ...) cluster.

**Comment by CyberDem0n** [comment]
It is not very dangerous to keep Etcd and Patroni/Postgres on the same server, although, I would recommend using different disks for them, so occasional spike of IO caused by Postgres doesn't affect Etcd (Etcd is very sensitive to write latency).

Pysyncobj is not producing so much IO activity, therefore less affected by Postgres, but I would probably still advise to keep `raft.data_dir` and `postgresql.data_dir` on different disks if it is possible.

**Comment by TonyGlob** [comment]
Thanks
