### ISSUE TITLE
Split-brain possible on simple configuration mistake

### ISSUE THREAD

**Issue by kmoppel** [zalando/patroni#1804]
Currently Patroni will happily launch a 2nd primary if the "member" name is by accident a duplicate of the current leader.

Sure it's an operator error...but I think would be relatively easy to avoid it by first checking the current leader's (if exists) role directly over the Patroni API.

This situation won't happen on new setups as there's seems to be a check against that (although the message "released leader key voluntarily as data dir empty and currently leader" hints that the new duplicate node still grabbed the key), but rather with a "takeover" of some old Postgres clusters where the PGDATA exists.

**To Reproduce**

1. Start the 1st node as leader.
2. Start a 2nd node that will be bootstrapped as replica.
3. Change the replica config so that the member name (`name`) matches the leader's name.
4. Restart Patroni on 2nd node

**Comment by mfpekala-nutanix** [comment]
I was able to reproduce this on the current version. I agree that it's operator error, but seems logical to check that a new node's name is unique when adding to a cluster. Am starting on a simple fix now.

**Comment by mfpekala-nutanix** [comment]
So far, I've been working on a fix that involves a pre-check during the initialization of a new-node to make sure there aren't any existing nodes in the cluster with the same name. However, it struck me that the root cause of the issue seems to be that in the DCS, nodes are simply storing their name, which causes two nodes to have the view of being the leader. Another solution is to make it so that instead of writing name to the DCS, there's some way of assigning UUIDs to nodes automatically, so two nodes can have the same name and be fine.

Was curious what people thought was the better solution here. Personally, I'm inclined to stick with the simple pre-check when adding a node to an existing cluster. I think the UUID is a bit of an overkill, given that patroni _probably_ isn't used for more than a few tens of nodes, max. I'm also not sure if this is an operator error we want to correct for, vs just error out + notify that the configuration is incorrect. Also UUIDs in general seem like more headaches down the road.

_But_, I can see how a UUID approach might get more at the "core" of the issue. Open to input!
