### ISSUE TITLE
Helm Chart?

### ISSUE THREAD

**Issue by TJM** [zalando/patroni#1833]
Where is the helm chart for patroni? All the examples I have seen are *very* outdated, and pointing to `incubator/patroni` (not even stable) on the deprecated (soon to be archived) helm/charts repo. I figured this would be the best place to ask :)

Tommy

**Comment by CyberDem0n** [comment]
I think the helm chart you are referring to (incubator/patroni) is actually a `spilo` helm chart rather than patroni, because in fact it uses the spilo image: https://github.com/zalando/spilo/releases

Personally I neither use nor like helm, therefore I am not interested in maintaining it.
If someone wants to take a responsibility for maintaining it I would advise to call it spilo helm chart and probably host in the spilo repository, or maybe even create a independent repo for it.

**Comment by TJM** [comment]
Understood, but now I am curious, what do you use to template/manage kubernetes resources if not helm?

**Comment by CyberDem0n** [comment]
We use [postgres-operator](https://github.com/zalando/postgres-operator) to run things at scale.
The postgresql CRD is quite small and doesn't require templating.
