### ISSUE TITLE
Enhancement Request - allow external sync replica

### ISSUE THREAD

**Issue by xzizka** [zalando/patroni#1836]
**Describe the enhancement request**
Patroni in version 2.0 and higher allow multiple sync replicas, but only with members of the Patroni cluster. For solutions where is required RPO=0 is mostly used streaming replication, where the backup tool (e.g. Barman) behaves like another replica.
To allow the backup tool run as a sync replica it is necessary add the slot to synchronous_standby_names. 
Patroni manage this parameter and fills it with names of the cluster nodes. Anything else is overwritten and that is why the backup tool can run only in asynchronous mode, which does not fulfill the RPO=0 requirement. 

**Expected behavior**
Add to Patroni a config variable which will include name of the external tool slot in synchronous_standby_names and during the failover/initialization/switchover of the cluster will add the slot for the external tool to allow sync replica approach.

**Environment**
- Patroni version: further versions
- PostgreSQL version: all
- DCS (and its version): all

**Comment by CyberDem0n** [comment]
Do you plan to work on it?

**Comment by xzizka** [comment]
I am DBA, not a programmer. I am not sure if I have enough knowledge to implement it. 
I can check the code and share the idea how to do that.

**Comment by CyberDem0n** [comment]
Since we don't really need this feature please don't expect that we will work on it.
This is an open source project, anyone could contribute, but taking into account that in 6 years you are the only one who asked for such a feature, please also don't expect that some random stranger will do it for you.

**Comment by xzizka** [comment]
Sure. I will check the code and discuss the way how can I do that. :-)

**Comment by xzizka** [comment]
I checked the code and am I right, that the content of the `synchronous_standby_names` is set in this function?
https://github.com/zalando/patroni/blob/583fccfb34a1b4e6de3a80a22997f1ea7b5478bc/patroni/postgresql/config.py#L1013

If yes, it seems to me, that I would change the code following way:
```
def set_synchronous_standby(self, sync_members, remote_sync_slot_name = null ):
        """Sets a node to be synchronous standby and if changed does a reload for PostgreSQL."""
        if sync_members and sync_members != ['*']:
            sync_members = [quote_ident(x) for x in sync_members]
        if self._postgresql.major_version >= 90600 and len(sync_members) > 1:
            sync_param = '{0} ({1})'.format(len(sync_members), ','.join(sync_members))
        else:
            sync_param = next(iter(sync_members), None)
>       if self._remote_sync_node != null:                                                           <
>           sync_param = sync_param + ',"' + remote_sync_slot_name + '"';       <
        if sync_param != self._synchronous_standby_names:
            if sync_param is None:
                self._server_parameters.pop('synchronous_standby_names', None)
            else:
                self._server_parameters['synchronous_standby_names'] = sync_param
            self._synchronous_standby_names = sync_param
            if self._postgresql.state == 'running':
                self.write_postgresql_conf()
                self._postgresql.reload()

```
Is this a good way?

I also see the parameter `synchronous_standby_names` in validator.py and test_potgres.py. It seems to me, that when I just add another node name to the parameter tests and validations can stay unchanged. Is that correct?

Maybe one idea... Should this be added to the DCS? Seems to me, that yes...

I am really sorry, but I am just DBA and not a programmer so please be patient with my approach and knowledge of how to work with Git and how to develop Patroni. Thank you.

**Comment by CyberDem0n** [comment]
World is more complex than people think.
Lets assume that currently `synchronous_standby_name` is set to `2 (node1,node2)`.
Where `node1`, and `node2` are members of Patroni cluster.
You suggest to change it unconditionally to the `3 (node1,node2,backup)`.

What will happen if the `backup` node is down? Right, primary would not be able to run transactions.
Is it really desired behaviour? I don't think so...

**Comment by xzizka** [comment]
> What will happen if the `backup` node is down? Right, primary would not be able to run transactions.
> Is it really desired behaviour? I don't think so...

Yes. It is. 
Because in core banking system you can somehow accept RTO>0. It is a big issue, sure, but more important is, that you can ensure RPO=0. 
It is crucial, that you MUST ensure, that no transaction is lost anywhere in the architecture/solution.
With Barman using synchronous streaming replication you have backup for every atomic transaction and then, you can say, that your solution is RPO=0, because even if you lose all nodes of the cluster, you can restore even the last committed transaction from Barman backup. If the streaming replication would be asynchronous, you can't ensure it.
That is why it is possible to "accept" the outage for write operations (read operations may still continue) when the `backup` node is down rather than lose any of the transaction.
I know, that nothing is 100%, but it is necessary to do maximum for it.

Can you please tell me if you will accept and merge my changes to the main branch? Does this make sense for you to have this in Patroni? 
This is not related to Barman only but to any tool using streaming replication for backup. And I know, that there will not be crowds of users of this feature. I will understand if you decline this. Thank you.

**Comment by CyberDem0n** [comment]
If your backup tool is not working properly primary becomes effectively read-only, which reducing the availability.
PRO=0 could be achieved not only with the help of your backup tool, but also by having normal synchronous replicas in the cluster.

Basically, it should not be unconditionally added to the synchronous_standby_names, but be considered as a virtual member of the cluster and handled by applying nearly the same rules as for other members.

**Comment by xzizka** [comment]
I agree that RPO=0 can't be achieved just with a backup tool and architecture needs to take into consideration synchronous replicas, but if you back up just WAL logs, you can lose some data in case you lose the whole cluster (which is more or less theoretical when you have geo cluster).
The only way how to ensure, that you backup all is to use sync replication (including the disadvantages you mentioned above), I think. 
This backup tool will not be considered during the switchover or failover of the cluster as a member of the cluster so will not affect the cluster itself. I would just consider it as a tool which accepts the cluster status "as-is" (established by Patroni) and just creates/uses an additional replication slot. Because of this, I don't think it should be considered as a part of the cluster even if it can affect it much. 
Maybe one more question...
If there would be 2 sync nodes and 2 async nodes in the cluster where replication will use a topology.
SYNC1 > ASYNC1
    |              
SYNC2  > ASYNC2
Will the fall of the backup tool triggers a failover process of the Patroni cluster? 
I would say that it will just stop writes because the backup tool would not be a part of Patroni and that is why it will not be considered in the health check process. 
Is this correct?

**Comment by CyberDem0n** [comment]
It looks like you are mixing a few different things:
1. replication slots
2. synchronous replication
3. HA

Somewhat being connected to each other they are actually don't depend on each other.
Creating the physical replication slot with an arbitrary name is possible and it will solve the problem of WAL retention required for a backup tool.

Synchronous replication is a different concept. The idea is that every transaction is persisted on more than one host in order to avoid a single point of failure.

In order to improve data durability, Patroni can leverage both concepts, replication slots, and synchronous replication.
Failure of any members except primary of Patroni cluster doesn't trigger a failover.

Currently, Patroni creates replication slots for all members which should be streaming from a given member if they are registered in DCS. On top of that, it [creates permanent replication slots](https://patroni.readthedocs.io/en/latest/SETTINGS.html) on the primary.

In case of synchronous replication being configured, Patroni takes responsibility for managing synchronous_standby_names. Only members that are keeping up with replication are put into synchronous_standby_names. The maximum number of sync members is limited by the [synchronous_node_count](https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-replication-factor). If the member is not keeping up or disconnected, it is removed from synchronous_standby_names and/or replaced with another member.

You tell, that we can lose the data if we lose all cluster members and the backup tool saves us from this scenario. Well, with the same probability you can lose the host where the backup tool is running with all the data.
In fact, by having a backup tool running on a different host you just slightly reducing the probability to lose all data, but the probability still exists.

The chances of the backup tool being down are absolutely the same as the chances of being down of any other host in the system. As I already explained, Patroni regularly maintains the synchronous_standby_names based on the state of the cluster and I don't see any single reason why the backup tool application_name should not be removed from the synchronous_standby_names is it is not streaming or lagging too much behind. Having other synchronous replicas available already gives us a guaranty of zero data loss.

**Comment by xzizka** [comment]
Thank you for this summary.
I agree with you, that replication slots != synchronous replication != HA

Replication slot is "tool", synchronous replication is "database process", HA is "process outside of the DB".

I played a little bit with Patroni and parameters like synchronous_node_count and with tags to affect the behaviour I need. I resolved everyting except for the position of Barman I want.

_You tell, that we can lose the data if we lose all cluster members and the backup tool saves us from this scenario. Well, with the same probability you can lose the host where the backup tool is running with all the data.
In fact, by having a backup tool running on a different host you just slightly reducing the probability to lose all data, but the probability still exists._
Absolutely agree. You can't ever achieve and guarantee 100% in any area.

_Currently, Patroni creates replication slots for all members which should be streaming from a given member if they are registered in DCS. On top of that, it creates permanent replication slots on the primary._
Create a replication slot is not an issue for Barman. It can do it itself. Barman behaves like another node in the cluster so here is a question how we should take it concerning other nodes of the cluster. 
The task here is how to ensure, that the slot/barman will be considered as a synchronous replica (leader will wait for a confirmation like from any other synchronous node), but will not be considered for failover. 
This brings me an idea to include tags (nosync: false, nofailover: true) in this situation. 

_Having other synchronous replicas available already gives us a guaranty of zero data loss._
Having only synchronous replicas does not cover the situation when the whole cluster is lost. We discussed, that there is a low probability this situation happens, but this is an advantage of this approach. You can guarantee, that even if all nodes of the cluster (with PostgreSQL) will be lost, you still have all data. 
Another question is, how is this requirement relevant in the current world with current technologies. Sure.
But thanks for this opinion. I saw several opinions on how the PRO=0 should look (architectural point of view) this is another one (without a backup as a part of the RPO=0). 

I think, that we can close this discussion at this point if you want. Thank you for your opinions and the explanation of some Patroni internals.
