### ISSUE TITLE
Support Matrix

### ISSUE THREAD

**Issue by 23RoboticRabbits** [zalando/patroni#1868]
Is there a patoni/postgres support matrix available?  Specifically is patroni 1.6.5 supported with postgres 13?

**Comment by bradnicholson** [comment]
There is not an support Matrix, but the release notes tell you when Major Version support is added.  PG 13 requires Patroni > 2.0.0.  See https://patroni.readthedocs.io/en/latest/releases.html#version-2-0-0

**Comment by CyberDem0n** [comment]
In theory, 1.6.5 might work with PG 13, but behavior could be suboptimal.
I don't really understand you want to run the version released nearly a year ago. Just take a look at release notes and try to count how many issues there were fixed since then.
And regarding the support matrix. Is there really a big value in it? The latest version supports anything starting from 9.3 and so far we never removed support of old Postgres versions.

**Comment by emrah83** [comment]
> In theory, 1.6.5 might work with PG 13, but behavior could be suboptimal. I don't really understand you want to run the version released nearly a year ago. Just take a look at release notes and try to count how many issues there were fixed since then. And regarding the support matrix. Is there really a big value in it? The latest version supports anything starting from 9.3 and so far we never removed support of old Postgres versions.

Sometimes we cannot upgrade Postgres Software Version because a legacy application may not support it. In such case we consider only upgrading Patroni. It would be nice to have compatibility matrix showing Patroni Version/Postgres Version.

But you said the newer versions are backwards compatible. Good to know. Thank you.
