### ISSUE TITLE
The Lag displayed by patroni is inconsistent with the pg_replication_slots.pg_wal_lsn_diff

### ISSUE THREAD

**Issue by cobolbaby** [zalando/patroni#1895]
**Describe the bug**

The lag displayed by patroni is inconsistent with the pg_replication_slots.pg_wal_lsn_diff. Which one is right?

**Expected behavior**

The value of the master-slave synchronization delay should be consistent.

**Screenshots**

- patronictl list
<img width="495" alt="屏幕快照 2021-03-21 下午10 53 53" src="https://user-images.githubusercontent.com/11460848/113009283-6337c800-91aa-11eb-9d7b-ee0c4c8f0c69.png">
- pg_replication_slots.pg_wal_lsn_diff
<img width="466" alt="屏幕快照 2021-03-30 下午10 52 46" src="https://user-images.githubusercontent.com/11460848/113009650-b742ac80-91aa-11eb-9936-a7091b284be7.png">

**Environment**
- Patroni version: 2.0.1
- PostgreSQL version: 10.15
- DCS (and its version): Etcd V2

**Comment by CyberDem0n** [comment]
patronictl calculates lag based on values stored in DCS, which are updated every loop_wait seconds.

The value stored in DCS for replicas could be described as: COALESCE(received_lsn, replayd_lsn).
- received_lsn is available only if replica is streaming.
- replayed_lsn is always available, but it could be behind the received_lsn.

The received_lsn is preferred because on failover we want to choose the replica which has more WAL available (to minimize the data loss).



I have no ide which field from pg_replication_slots you have used.

**Comment by cobolbaby** [comment]
@CyberDem0n  pg_wal_lsn_diff refers to `pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)`

https://github.com/prometheus-community/postgres_exporter/blob/1dc210476ebd630aec7feff4c4487163724aedd3/cmd/postgres_exporter/postgres_exporter.go#L431-L439
