### ISSUE TITLE
Codacy dashboard

### ISSUE THREAD

**Issue by tnir** [zalando/patroni#1913]
While the project is pushing the results to Codacy on GitHub Actions, I could not find anything at https://app.codacy.com/gh/zalando/patroni/dashboard or https://www.codacy.com/app/zalando/patroni. How can we find the Codacy's dashboard for this repository?

**Comment by CyberDem0n** [comment]
Here it is: https://app.codacy.com/manual/patroni/patroni/dashboard

The thing is that codacy has been changing "rules" a few times. Originally (4 or 5 years ago), it just worked. Later they forced everybody to create manual organizations and I ended up creating "patroni" org.
Now we are supposed to use "zalando" org with codacy, but it requires admin privileges in order to install it. As a result for now we stuck with "legacy".

**Comment by tnir** [comment]
Thanks @CyberDem0n, closing in favor of #1914.
