### ISSUE TITLE
PG wal automatic deleting

### ISSUE THREAD

**Issue by zhanshen8D** [zalando/patroni#1941]
Postgres will generate wal files if there are insert/update/delete operations. And Postgres will delete the WAL files automatically after checkpoint.
But if PG is working with streaming replication and one or more replication is down, the automatic WAL deleting will NOT happen.
Thus there will be more and more WAL files unless the replication is recovered or disk is full.

Have Patroni ever thought about this kind of scenario and recovering the replication on software level?
Thanks.

**Comment by CyberDem0n** [comment]
First of all, it is not a task of Patroni to monitor the disk space.
Patroni does its best to keep the primary and all replicas up and running.
If the replica is down (Patroni is down), the primary will drop the replication slot and therefore there will be nothing that prevents WALs from recycling.
But, there might be a case that for some reason postgres on the replica doesn't stream from the primary. This is also something that you have to monitor and fix.

You should not expect that Patroni could replace human and monitoring solutions for 100%.
Think about it as an auto-pilot. If all systems on the plane are properly working, the auto-pilot does 99% of the pilot job, but, if something goes wrong you better know how to fly manually.

**Comment by Wrhector** [comment]
FYI @zhanshen8D there is a new parameter in pg13 that allows you to limit the amount of wal files a replication slot can hold from deletion: https://postgresqlco.nf/doc/en/param/max_slot_wal_keep_size/ This can help prevent disk full issues.

**Comment by dberardo-com** [comment]
from the link shared: 

> Specify the maximum size of WAL files that replication slots are allowed to retain in the pg_wal directory at checkpoint time.

is this the max size of the pg_wal folder? is it a bit ambiguous the way they describe it

> Otherwise, if restart_lsn of a replication slot falls behind the current LSN by more than the given size, the standby using the slot may no longer be able to continue replication due to removal of required WAL files.

does it mean that after a certain time/size of missing logs the replica will not be able to come back online anymore even if it reconnects to the cluster? i.e. a "patronictl reinit"  command is needed at that point?

and also: is it possible to configure the "restart_lsn" in patroni, so that the replicas coming back online are always able to discard their changes and stream from the new wal ?
