### ISSUE TITLE
Patroni run cycle is blocked

### ISSUE THREAD

**Issue by cobolbaby** [zalando/patroni#1984]
**Describe the bug**

There is a three-node Patroni cluster. One of the nodes, `pg1203`, was caught in an unknown exception last night. The service container no longer outputs logs in a loop, and it feels like it is stuck. After some hours, another node `pg1202` which is the leader was also stuck.

This situation has continued to the present. In this case, no matter what the patronictl command is executed, it is in the pending state.

Fortunately, although the raft or patroni is abnormal, the status of the cluster has not been switched, and services can still be provided to the outside world.

**To Reproduce**

**Expected behavior**

**Screenshots**
![2021-06-28 17-56-09屏幕截图](https://user-images.githubusercontent.com/11460848/123617757-2c6d5e80-d83a-11eb-9c9b-c4ca3fe6e99c.png)

**Environment**
- Patroni version: 2.0.2
- PostgreSQL version: 12.7
- DCS (and its version): Raft

**Comment by cobolbaby** [comment]
In this case, how can I debug the problem?

**Comment by CyberDem0n** [comment]
> was caught in an unknown exception last night.

It is a bit strange to see _screenshots_ instead of the actual exception...

**Comment by cobolbaby** [comment]
The main reason is that I don't know what causes run_cyle to not work properly. And there is no suspicious `ERROR` or `FATAL` in the PG log

**Comment by CyberDem0n** [comment]
> I don't know what causes run_cyle to not work properly.

I don't know it either. It could depend on many factors including the PySyncObj version used and the Patroni config.
Some issues were for example fixed in the master branch.

**Comment by cobolbaby** [comment]
Is there any way I can view the console output of PySyncObj, for example, I can adjust the `PATRONI_LOG_LEVEL`?

**Comment by cobolbaby** [comment]
When I restarted the cluster, there seemed to be a problem with the synchronization between the nodes:

- logs

```
2021-06-28 19:31:57,065 INFO: My wal position exceeds maximum replication lag
2021-06-28 19:31:57,177 INFO: following a different leader because i am not the healthiest node
2021-06-28 19:31:59,382 DEBUG: API thread: 10.13.207.227 - - "OPTIONS /replica HTTP/1.0" 200 - latency: 5.610 ms
2021-06-28 19:32:02,390 DEBUG: API thread: 10.13.207.227 - - "OPTIONS /replica HTTP/1.0" 200 - latency: 5.537 ms
2021-06-28 19:32:05,397 DEBUG: API thread: 10.13.207.227 - - "OPTIONS /replica HTTP/1.0" 200 - latency: 5.424 ms
2021-06-28 19:32:08,405 DEBUG: API thread: 10.13.207.227 - - "OPTIONS /replica HTTP/1.0" 200 - latency: 5.373 ms
2021-06-28 19:32:11,413 DEBUG: API thread: 10.13.207.227 - - "OPTIONS /replica HTTP/1.0" 200 - latency: 5.111 ms
2021-06-28 19:32:14,424 DEBUG: API thread: 10.13.207.227 - - "OPTIONS /replica HTTP/1.0" 200 - latency: 5.409 ms
```
- patronictl list

```
+ Cluster: pgcluster_itc_12 (6904565379678310425) +-----------+
| Member | Host          | Role    | State   | TL | Lag in MB |
+--------+---------------+---------+---------+----+-----------+
| pg1201 | 10.13.208.218 | Replica | running | 33 |        30 |
| pg1202 | 10.13.208.219 | Replica | running | 35 |         0 |
| pg1203 | 10.13.208.220 | Replica | running | 33 |        30 |
+--------+---------------+---------+---------+----+-----------+
```

**Comment by huiyalin525** [comment]
> patronictl list
>+ Cluster: pgcluster_itc_12 (6904565379678310425) +-----------+
>| Member | Host          | Role    | State   | TL | Lag in MB |
>+--------+---------------+---------+---------+----+-----------+
>| pg1201 | 10.13.208.218 | Replica | running | 33 |        30 |
>| pg1202 | 10.13.208.219 | Replica | running | 35 |         0 |
>| pg1203 | 10.13.208.220 | Replica | running | 33 |        30 |
>+--------+---------------+---------+---------+----+-----------+
Why have three replica nodes？
 I think your patroni has the main just raft storage there is an exception, because pg1202 lag is 0 and log information
so，I tried to do
1. I first stop a node 
2. I use the syncobj_admin -conn ip:port remove ip:port command to delete this node 
3. Restart this node to execute the command patronictl list to find that the cluster is healthy and lag becomes 0. I don't know if it's right

**Comment by huiyalin525** [comment]
> patronictl list
>+ Cluster: pgcluster_itc_12 (6904565379678310425) +-----------+
>| Member | Host          | Role    | State   | TL | Lag in MB |
>+--------+---------------+---------+---------+----+-----------+
>| pg1201 | 10.13.208.218 | Replica | running | 33 |        30 |
>| pg1202 | 10.13.208.219 | Replica | running | 35 |         0 |
>| pg1203 | 10.13.208.220 | Replica | running | 33 |        30 |
>+--------+---------------+---------+---------+----+-----------+


Why have three replica nodes？
 I think your patroni has the main just raft storage there is an exception, because pg1202 lag is 0 and log information
so，I tried to do
1. I first stop a node 
2. I use the syncobj_admin -conn ip:port remove ip:port command to delete this node 
3. Restart this node to execute the command patronictl list to find that the cluster is healthy and lag becomes 0. I don't know if it's right

**Comment by huiyalin525** [comment]
> patronictl list
> Cluster: pgcluster_itc_12 (6904565379678310425) +-----------+
> | Member | Host | Role | State | TL | Lag in MB |
> +--------+---------------+---------+---------+----+-----------+
> | pg1201 | 10.13.208.218 | Replica | running | 33 | 30 |
> | pg1202 | 10.13.208.219 | Replica | running | 35 | 0 |
> | pg1203 | 10.13.208.220 | Replica | running | 33 | 30 |
> +--------+---------------+---------+---------+----+-----------+

Why have three replica nodes？
I think patroni has the leader ，it is raft storage  there is an exception, because pg1202 lag is 0 and  check the log information
so，I tried to do

-  first stop a node

-  use the syncobj_admin -conn ip:port remove ip:port command to delete this node

- Restart this node to execute the command patronictl list to find that the cluster is healthy and lag becomes 0. I don't know if it's right

**Comment by huiyalin525** [comment]
> patronictl list
> Cluster: pgcluster_itc_12 (6904565379678310425) +-----------+
> | Member | Host | Role | State | TL | Lag in MB |
> +--------+---------------+---------+---------+----+-----------+
> | pg1201 | 10.13.208.218 | Replica | running | 33 | 30 |
> | pg1202 | 10.13.208.219 | Replica | running | 35 | 0 |
> | pg1203 | 10.13.208.220 | Replica | running | 33 | 30 |
> +--------+---------------+---------+---------+----+-----------+

Why have three replica nodes？
I think patroni has the leader ，it is raft storage there is an exception, because pg1202 lag is 0 and check the log information
so，I tried to do

- first stop a node
- use the syncobj_admin -conn ip:port -remove ip:port command to delete this node
- Restart this node to execute the command patronictl list to find that the cluster is healthy and lag becomes 0. I don't know if it's right

**Comment by cobolbaby** [comment]
Indeed, the root cause is the synchronization problem of the raft cluster. 

Finally, it needs to be restored by rebuilding the raft.
