### ISSUE TITLE
synchronous replication + tags

### ISSUE THREAD

**Issue by ujangja** [zalando/patroni#2012]
I have 3 nodes patroni cluster, tried to modify synchronous_standby_names: first 1 (patroni3) instead of * ; but it wont apply to the cluster.

I plan to have 4 replica nodes which are 2 in DC and 2 in DRC, I want to ensure that patroni will not choose the DRC one as sync mode.

exploring change nosync tags for a member node; didnt find how to do it....anyone can share? 

Since I deployed this cluster in docker swarm, I have to create a generic patroni.yml file in image, if I modify some parameters that are different than patroni.yml; will it persists in DCS? or everytime cluster restart should we change it again?

**Comment by CyberDem0n** [comment]
> tried to modify synchronous_standby_names: first 1 (patroni3) instead of * ; but it wont apply to the cluster.

Because it is managed by Patroni, please read the docs: https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode

> I plan to have 4 replica nodes which are 2 in DC and 2 in DRC, I want to ensure that patroni will not choose the DRC one as sync mode.

You have to put `tags.nosync` to the Patroni config files in DRC.

> Since I deployed this cluster in docker swarm, I have to create a generic patroni.yml file in image

Well, tags are nodes specific, they don't work with a generic config file by definition.

> if I modify some parameters that are different than patroni.yml; will it persists in DCS?

Of course not. For existing clusters patroni.yml is never persisted in DCS. For absolutely new clusters only the `bootstrap.dcs` section is written to the /config key in DCS.

I would highly recommend you to go through the tutorial: https://github.com/patroni-training/2019

**Comment by ujangja** [comment]
hm....looks like we have to manage many docker images...?

**Comment by CyberDem0n** [comment]
Well, you can generate the config based on environment variables passed.

**Comment by ujangja** [comment]
Thanks for the clue, im using volume bind to have different patroni.yml for sync mode.

I looking httpcheck result in haproxy to let readonly port to bind to only sync nodes...is there any special return code for this requirement?

**Comment by CyberDem0n** [comment]
The `GET /synchronous` endpoint will do it: https://patroni.readthedocs.io/en/latest/rest_api.html#health-check-endpoints
