### ISSUE TITLE
Add HTTP HEAD support to API

### ISSUE THREAD

**Issue by caseyandgina** [zalando/patroni#2021]
It would be advantageous if the Patroni API could support the HTTP HEAD method.  I am told this would result in less work for our load balancers to have to do when running the health checks, as only the status code matters to them, not the JSON information.  Is this something that's plausible to add?

```
$ curl -I http://d-gp2-dbpgdba1-1.imovetv.com:8008/patroni
HTTP/1.0 501 Unsupported method ('HEAD')
Server: BaseHTTP/0.6 Python/3.8.5
Date: Wed, 28 Jul 2021 19:17:57 GMT
Connection: close
Content-Type: text/html;charset=utf-8
Content-Length: 497

$ curl -s -o /dev/null -w "%{http_code}" http://d-gp2-dbpgdba1-1.imovetv.com:8008/patroni
200
```

**Comment by CyberDem0n** [comment]
Hi @caseyandgina we already [support](https://patroni.readthedocs.io/en/latest/rest_api.html#health-check-endpoints) the OPTIONS request method:
```
postgres@6b73d9e5ada2:~$ curl -v -XOPTIONS http://localhost:8008/primary
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8008 (#0)
> OPTIONS /primary HTTP/1.1
> Host: localhost:8008
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< 
* Closing connection 0

postgres@6b73d9e5ada2:~$ curl -v -XOPTIONS http://localhost:8008/replica
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8008 (#0)
> OPTIONS /replica HTTP/1.1
> Host: localhost:8008
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
< 
* Closing connection 0
```

**Comment by caseyandgina** [comment]
I'm not sure whether that is something that the load balancers (F5) can support but I'll ask them to look into it.

That said, I found this in the RFC for it:
> The response body, if any, SHOULD also include information about the communication options. The format for such a body is not defined by this specification, but might be defined by future extensions to HTTP.

Given this, I think that HEAD support would still be preferable, as it would avoid any unnecessary fetching of body when only the status code is needed.  It seems that it would be a misuse of OPTIONS to use it for performing a health check, although it may work.

**Comment by CyberDem0n** [comment]
> I'm not sure whether that is something that the load balancers (F5) can support but I'll ask them to look into it.

F5 allows constructing arbitrary health check requests.

> Given this, I think that HEAD support would still be preferable, as it would avoid any unnecessary fetching of body when only the status code is needed. It seems that it would be a misuse of OPTIONS to use it for performing a health check, although it may work.

Well, I would really argue with that, OPTIONS is sent by default by HAProxy, which is probably the most popular load balancer in the world.

**Comment by jocutajar** [comment]
Hi folks, 

DL;DR: To me it seems clearly as a misuse of the OPTIONS method and misleading while HEAD is appropriate.

The fact that HAProxy uses this by default is IMO a flawed argument. Sending OPTIONS request to any web server is probably the safest choice considering the potential undesirable side effects of GET/HEAD. HAProxy probably only needs to establish the fact that there is indeed SOME web server listening on a given port and OPTIONS does that well. As soon as you get into specifying a concrete health check endpoint, the first example guides you to use the GET method. See https://www.haproxy.com/documentation/hapee/latest/load-balancing/health-checking/active-health-checks/#check-an-http-service

Please check what the specs say about OPTIONS: 
- https://www.rfc-editor.org/rfc/rfc9110.html#name-options
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

HEAD is precisely what we want, like GET, but without the body. On a given endpoint I would expect OPTIONS to always return the same result, regardless of the application health. The original idea is that it would tell the client which methods can be used on the resource (with potential extensions). It was not meant to fail because for instance the DB is read-only. In practical words, OPTIONS /health should always come back with HTTP 200 and `Allow: OPTIONS, GET, HEAD`. GET and HEAD should fail with HTTP 5xx to indicate problems with the application. GET would provide additional diagnostic details in the body.

I understand that implementing OPTIONS is useful because it's the default in HAProxy on the `*` or `/` resource, but it should serve just as an ACK - "yp, someone on the wire". I'd suggest a compromise - to avoid the implementation overhead, you could simply treat OPTIONS and HEAD equally for a start, while replacing OPTIONS with HEAD in docs.
I guess there is one more benefit of OPTIONS - that it is not cache-able by spec. This is easily compensated for with cache control headers in the response to GET/HEAD.

I came to this issue as I was going to create the same. Being a good on-line citizen, I checked for existing issues first. When I use the GET method in haproxy to check the patroni endpoints it generates a lot of noise in the logs. Being the smart ass I am I tried the HEAD method - boom, not there. I would intuitively assume that I should be able to get HEAD if I can get GET.

> 2022-07-13_16:45:38.68337 2022-07-13 16:45:38,683 WARNING: Exception happened during processing of request from 172.31.45.250:32774
> 2022-07-13_16:45:38.68374 2022-07-13 16:45:38,683 WARNING: Traceback (most recent call last):
> 2022-07-13_16:45:38.68377   File "/opt/gitlab/embedded/lib/python3.9/socketserver.py", line 683, in process_request_thread
> 2022-07-13_16:45:38.68377     self.finish_request(request, client_address)
> 2022-07-13_16:45:38.68377   File "/opt/gitlab/embedded/lib/python3.9/socketserver.py", line 360, in finish_request
> 2022-07-13_16:45:38.68377     self.RequestHandlerClass(request, client_address, self)
> 2022-07-13_16:45:38.68378   File "/opt/gitlab/embedded/lib/python3.9/socketserver.py", line 747, in __init__
> 2022-07-13_16:45:38.68378     self.handle()
> 2022-07-13_16:45:38.68378   File "/opt/gitlab/embedded/lib/python3.9/http/server.py", line 427, in handle
> 2022-07-13_16:45:38.68378     self.handle_one_request()
> 2022-07-13_16:45:38.68379   File "/opt/gitlab/embedded/lib/python3.9/site-packages/patroni/api.py", line 634, in handle_one_request
> 2022-07-13_16:45:38.68379     BaseHTTPRequestHandler.handle_one_request(self)
> 2022-07-13_16:45:38.68379   File "/opt/gitlab/embedded/lib/python3.9/http/server.py", line 415, in handle_one_request
> 2022-07-13_16:45:38.68379     method()
> 2022-07-13_16:45:38.68379   File "/opt/gitlab/embedded/lib/python3.9/site-packages/patroni/api.py", line 178, in do_GET
> 2022-07-13_16:45:38.68380     self._write_status_response(status_code, response)
> 2022-07-13_16:45:38.68380   File "/opt/gitlab/embedded/lib/python3.9/site-packages/patroni/api.py", line 94, in _write_status_response
> 2022-07-13_16:45:38.68381     self._write_json_response(status_code, response)
> 2022-07-13_16:45:38.68381   File "/opt/gitlab/embedded/lib/python3.9/site-packages/patroni/api.py", line 53, in _write_json_response
> 2022-07-13_16:45:38.68381     self._write_response(status_code, json.dumps(response, default=str), content_type='application/json')
> 2022-07-13_16:45:38.68381   File "/opt/gitlab/embedded/lib/python3.9/site-packages/patroni/api.py", line 50, in _write_response
> 2022-07-13_16:45:38.68382     self.wfile.write(body.encode('utf-8'))
> 2022-07-13_16:45:38.68382   File "/opt/gitlab/embedded/lib/python3.9/socketserver.py", line 826, in write
> 2022-07-13_16:45:38.68382     self._sock.sendall(b)
> 2022-07-13_16:45:38.68382 ConnectionResetError: [Errno 104] Connection reset by peer
> 2022-07-13_16:45:38.68383 

Please reopen the issue :) and make the world a better place.

**Comment by CyberDem0n** [comment]
@jocutajar everything you write makes sense, but...
The problem is that HAProxy simply closes the socket after receiving the first line of HTTP response, therefore we get plenty of exceptions in Patroni logs when it tries to send headers and body.
We simply abuse OPTIONS to identify that request was sent by HAProxy and respond to it only with `HTTP/1.0 200 OK` or `HTTP/1.0 503 Service Unavailable`.

Yes, we can add the HEAD support, which will work similar to GET but without sending a body with JSON, but once you update HAProxy config you'll immediately see tons of exceptions in the Patroni log.

>This is easily compensated for with cache control headers in the response to GET/HEAD.

Not with HAproxy, as I already told it discards everything except the first line of response by simply closing the socket.

> Please reopen the issue :) and make the world a better place.

There is just one way to make the world better, open a PR implementing changes you want ;)

**Comment by jocutajar** [comment]
I see. There will probably be a way to make haproxy consume the rest of the stream with some header capture, like this for instance https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#7.3.6-res.hdr_names or on patroni side, the exception could be handled and lowered to debug level as it has no impact.
