### ISSUE TITLE
Failover option when master lost dsc in async mode

### ISSUE THREAD

**Issue by skilyazhnev** [zalando/patroni#2070]
Hello!
Firstly, thanks for this awesome soft.

Secondly:
 
I was testing patroni failover with the "leader lost dsc" scenario.
It looks like:
1) I use stack patroni -> local_consul_agent on 3 patroni's nodes (in my case load isn't huge and i can install dsc with patroni).
2) I kill only leader node consul (when leader patroni still work)
3) I wait for TTL*2 
4) I would like to see new leader

And I faced problem. When I kill consul agent on the leader node, all patroni standby think that they are too far from leader node. And they can't election new leader.
although i configure parametr 'maximum_lag_on_failover: 1048576000` (replication gap between node near to 0)

I see in log messages like: 
```log
Sep 27 14:17:47 skilyazhnev-pat-2 patroni[49424]: 2021-09-27 14:17:47,941 INFO: Got response from skilyazhnev-pat-1 http://20.10.12.106:8008/patroni: {"state": "running", "postleader_start_time": "2021-09-27 14:15:47.899882+03:00", "role": "replica", ">
Sep 27 14:17:47 skilyazhnev-pat-2 patroni[49424]: 2021-09-27 14:17:47,942 INFO: Got response from skilyazhnev-pat-3 http://20.10.12.141:8008/patroni: {"state": "running", "postleader_start_time": "2021-09-27 14:16:08.275375+03:00", "role": "replica", ">
Sep 27 14:17:48 skilyazhnev-pat-2 patroni[49424]: 2021-09-27 14:17:48,025 INFO: Wal position of skilyazhnev-pat-3 is ahead of my wal position
Sep 27 14:17:48 skilyazhnev-pat-2 patroni[49424]: 2021-09-27 14:17:48,046 INFO: following a different leader because i am not the healthiest node
```
And all patroni cluster nodes "freeze" in read only state. 
In sync_replication_mod that problem solved (in this issue people told about that: [issue-1054](https://github.com/zalando/patroni/issues/1054) ).

My simple config:
<details><summary>patroni_edit_config.yml</summary>
<p>

```yml
loop_wait: 10
maximum_lag_on_failover: 1048576000
pg_hba:
- host replication replicator 0.0.0.0/0 md5
- host all all 0.0.0.0/0 md5
- host all postgres 0.0.0.0/0 md5
postgresql:
  parameters:
    hot_standby: 'on'
    max_connections: 1000
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_keep_segments: 8
    wal_level: hot_standby
    wal_log_hints: true
  use_pg_rewind: true
retry_timeout: 5
ttl: 23
```
</p>
</details>

If patroni really can't failover in this case I think good idea talk about option for this because:
1) I can restart one of patroni standby and then it changes to a leader (and I think people just do it with bash script)
2) In consul case we depend on one agent (Or in other dsc if we get split of between leader and dsc nodes)
3) Patroni is positioned as a template for PG and the ability to consciously customize this case should be present. 

Or is it too difficult to realization?

Thanks in advance for your reply.

**Comment by CyberDem0n** [comment]
> When I kill consul agent on the leader node, all patroni standby think that they are too far from leader node. 

It has been discussed many times. Don't shoot your own foot. Consul agent is a dependency and you have to make make it available/reliable.

Of course, there is always an option to use Etcd, where Patroni doesn't have to deal with intermediate proxy component and connects directly to Etcd nodes.

**Comment by skilyazhnev** [comment]
Thanks for fast reply.

> Consul agent is a dependency

But you still handler this for sync_mod. Why you work with dependency in sync case and drop it in async case?
I can accept it if this too hard for realize for special async.. But this project already handling case with lost dependency DSC.

**Comment by CyberDem0n** [comment]
I am tired explaining it one more time. Please find one of my answers in closed issues

**Comment by skilyazhnev** [comment]
Maybe then this issue will be part of the solution?
If you are bored with these questions, then they are frequent. I am neither the first nor the last.

Just write in the documentation that "an application cannot downgrade a running legacy leader if it is running separately from DSC (only in asynchronous replication mode in some cases)." And then you can send people to the documentation where you explained it once. I did not find this, and judging because I was not immediately wrapped there, it is not there. 

This is not only true for the consul, I can imagine a situation where your network will disconnect the keystore from the leader, albeit less likely.

thanks for the answer, anyway.

**Comment by CyberDem0n** [comment]
@skilyazhnev Patroni is an open-source project, any contributions (especially documentation) are always welcome.

Regarding Consul agent. The issue is that when being shutdown cleanly (with SIGTERM), it immediately invalidating all sessions created via this agent, what makes the leader key to expire. Since all replicas are watching for leader key changes, they are immediately notified about the missing leader key. It triggers the leader race.
But, in fact, the old leader still didn't realize that it is not allowed to run as a primary anymore, it will take up to loop_wait + retry_timeout before it will start demoting.
Luckily, every replica keeps the information about the old leader in memory and they are also using it in order to double-check that the old leader is really passed away. They contact it via the REST API, see that it is still running as a primary and in order to minimize chances of split-brain they update `primary_conninfo` and restart/reload postgres. From this moment all replicas become stale.
Later, the old leader realizes that it has to demote and does that. But, in fact it is ahead of all replicas.
At the same time replicas continue doing the leader race and every time they include the former leader into the list of nodes they have to race against. All replicas correctly notice that the former leader is ahead of them and if they would promote, it would become a clear data loss. So you end up in having logs like you posted.

Synchronous replication is a different case. We know for sure that there should be no transactions reported to the client that was not acknowledged by the synchronous node. Hence, it is safe to promote the sync node even if the old primary was a bit ahead (no data loss that was visible to clients).

**Comment by dbary** [comment]
very interesting scenario. I am tempted to test this on my own.
 
@skilyazhnev , few things to test

1) Did you try increasing maximum_lag_on_failover while this was going on. I guess leader node selection will go ahead if this value is higher than the lag replicas had at that moment. 

2) if you did not do 1) and try restarting consul agent  on the old leader node, and if that succeeds, can it become a leader node again ?

My point is we have to get out of this situation somehow since we can't afford to have all read only db's.

Question for @CyberDem0n, would we run into the same situation if we loose postgres on the leader node and there was a lag on replicas when it happened, so leader node selection would still fail?

Thanks
Dinesh
