### ISSUE TITLE
issue with zookeeper node creation

### ISSUE THREAD

**Issue by sandeepkalra** [zalando/patroni#2096]
Hi, 

I have a working postgres-12 code base with patroni:2.0.1 and kazoo:7.6.2

I recently tried to migrate to postgres-14 with patroni:2.1.1 and kazoo:7.8.0, and seeing failures in patroni to unable to bring things up. The debug logs were enabled, and patroni.log file is attached. 
[patroni.log](https://github.com/zalando/patroni/files/7385721/patroni.log)
From logs it appears that the error from zookeeper is NoNodeExists. However, this specific node `<>/status` was  never created. I also tried "patronictl remove <cluster>" to check. Can someone please guide me what may have changed in these 2 versions that may be causing it. 

[Edit] Zookeeper version is 3.6.2 and has not changed between the old and new project changes.
The yaml file between the two projects is also exactly same too.

Thanks,

**Comment by CyberDem0n** [comment]
What made you think that the problem is with zookeeper/kazoo?
Due do over-excessive debug logs you don't see the wood for the trees. 
Postgres apparently failed to start, but it seems that you never check its logs.

If you think that you can do a major upgrade by updating bin_dir - you are also wrong: https://patroni.readthedocs.io/en/latest/existing_data.html#major-upgrade-of-postgresql-version

**Comment by sandeepkalra** [comment]
sorry, I meant I was not able to find "Postgres logs" as the Postgres tasks
never get started. I do have patroni logs that I have already given.
---
Best Regards,
Sandeep Kalra

**Comment by CyberDem0n** [comment]
If postgres fails to start it either writes the reason to stderr or to the log. And it is your responsibility to figure out why it doesn't start.
Right now you are blaming the auto-pilot that it can't start failed airplane engines.

**Comment by sandeepkalra** [comment]
Thanks. I will look into stderr for more details.
