### ISSUE TITLE
Question: Benchmark for number of clusters handled through Patroni/etcd cluster

### ISSUE THREAD

**Issue by pearlsprathap** [zalando/patroni#2273]
Hi All, I have a question about benchmark done(if any) on how many number of PostgreSQL clusters, we expect a single etcd cluster can handle with acceptable performance. We are looking to adopt Patroni as a solution for our postgreSQL clusters, so we are looking for this information.

We have close to 3000+ PostgreSQL clusters and planning for a 5 or 7 node etcd cluster spread across regions. So we are thinking if we should have multiple etcd clusters to segregate the PostgreSQL clusters for optimal performance. Any insight will be very helpful. Thank you.

Regards,
Prathap

**Comment by CyberDem0n** [comment]
Let's assume that 3k+ clusters would result in 9k+ nodes.
Also lets assume that Patroni is running with default settings: loop_wait=10s, retry_timeout=10s, ttl=30s

For Etcd v2:
1. Every node will fetch keys for the given cluster every 10s - 900+ reads/s
2. Every node will update the `/member` key every 10s, which would result in 900+ writes/s.
3. In addition to that there is an update of the `/leader` key and maybe the `/status` (for idle clusters LSN isn't moving forward and update isn't required) key every 10s - which would give 1800+ writes/s

In total, there would be 900+ reads/s and 2700+ writes/s for 3k clusters with 9k nodes.


For Etcd v3:
1. Patroni doesn't fetch keys every 10s, but receives updates via the long-polling connection. The initial read happens only when the connection to etcd cluster is established.
2. Every node updates the session
3. Every node maybe updates the `/member` key (for idle clusters LSN isn't moving forward and update isn't required)
4. The leader node maybe updates the `/status` key (for idle clusters LSN isn't moving forward and update isn't required)

In total, there would be 900+ updates/s of the sessions and up to 1800+ writes/s for 3k clusters with 9k nodes. The number of reads would be significantly smaller than 900/s.

IMO, it shouldn't be a problem to achieve these numbers with a single etcd cluster. But, please make sure that etcd nodes are using storage that can provide enough performance. The other side of the problem is that outage of a single etcd cluster will bring all Patroni clusters to read-only, hence maybe it would be better to have split them to some smaller groups.

**Comment by pearlsprathap** [comment]
Hi @CyberDem0n ,

Thanks a lot for your useful insights, we will explore your recommendations further and setup accordingly.
