### ISSUE TITLE
Future upgrades - always replicas then leader?

### ISSUE THREAD

**Issue by drnic** [zalando/patroni#240]
From v1.0 release notes:

> When upgrading from v0.90 or below, always upgrade all replicas before the master. Since we don't store replication credentials in DCS anymore, an old replica won't be able to connect to the new master.

Is this requirement just for upgrading to v1.0 because of change in where replicas get credentials for leader? Or will this "replicas first, leader last" requirement be for all future updates too?

I ask because we run a fleet of patroni clusters randomly scheduled in docker containers across a fleet of machines. We've not coded a deterministic upgrade sequence - rather containers on a specific machine (some leaders and some replicas) will be upgraded, then it moves on to upgrade other machines and their containers. Our workaround for the v1.0 upgrade might be to do disaster recovery - destroy everything, and rebuild all clusters from wal-e backups. So, currently am wondering if this issue will reoccur for future patroni v1.X releases?

**Comment by alexeyklyukin** [comment]
Hi,

> On 06 Jul 2016, at 02:13, Dr Nic Williams <notifications@github.com> wrote:
> 
> From v1.0 release notes:
> 
> When upgrading from v0.90 or below, always upgrade all replicas before the master. Since we don't store replication credentials in DCS anymore, an old replica won't be able to connect to the new master.
> 
> Is this requirement just for upgrading to v1.0 because of change in where replicas get credentials for leader? Or will this "replicas first, leader last" requirement be for all future updates too?
> 

Generally, this is a reasonable thing to do on any upgrade, since you don’t want an upgrade-related accident to kill your master, and rather have it first tried on the replicas. That being said, the notice above is related specifically to the change of what Patroni stores in  DCS, so it’s very likely that the future upgrades will not require doing things in this particular order.

Kind regards,
--
Oleksii Kliukin | 5432 Engineer | phone: +4917612759799 |  hipchat: @OleksiiKliukin
