### ISSUE TITLE
question: patroni increase TL after restart patroni service

### ISSUE THREAD

**Issue by bagafoot** [zalando/patroni#2563]
Hello,
I wonder why patroni is increasing postgresql time line in every restart, is it right aproach?
Is there any configuration to prevent this.

Enviroment
patroni 3.0.0
postgresql 12.14
etcdctl version: 3.3.11
API version: 2

**Comment by CyberDem0n** [comment]
The main purpose of issue template is collecting as much details about your setup as possible with the minimal effort.
Whatever you describe on your own isn't enough.
Restart of patroni service is the same as stop+start. When stopped gracefully Patroni also stops postgres, because postgres must not run unsupervised. If primary isn't  running it cases a failover.
