### ISSUE TITLE
Callbacks for write operations

### ISSUE THREAD

**Issue by jaredcurtis** [zalando/patroni#259]
We've started evaluating patroni as part of our highly available postgres cluster. I'm considering taking on a potentially messy set of changes to isolate all write operations (including `pg_ctl` and similar) into a set of callback scripts similar to how `on_role_change` and the like are handled. This way we can run patroni as a limited user and allow/deny changes using sudo (or other scripted logic).

Would this be something that would be a candidate for acceptance upstream?

**Comment by alexeyklyukin** [comment]
This is more complex, than just moving pg_ctl calls into callbacks. Patroni reads and writes files (such as .pgpass, PostgreSQL configuration, postmaster.opts, postmaster.pid, pg_hba, PG_VERSION), creates and writes temp files, as well as lists directories. It also rename files (i.e. postgresql.conf to postgresql.base.conf), and removes them (.ready files in case of pg_rewind). 

In order to perform those operations, Patroni needs permissions of the owner of the data directory, in other words, those operations needs to be moved into the callbacks/abstracted as well. One way to do it would be to incapsulate filesystem operations into the separate class, and make user-defined callbacks inherit from it.
