### ISSUE TITLE
wal_archive directory out of disk space

### ISSUE THREAD

**Issue by ovidiucp** [zalando/patroni#264]
Is there a way to automatically remove the archived WAL files in the wal_archive directory?

I've run out of disk space on the master, so I temporarily disabled archive_mode.

What is the best way to deal with this problem?

**Comment by CyberDem0n** [comment]
How does your `archive_command` looks like?
It's very strange to keep archived WAL files on the same host where the master runs. If the machine dies you will loose them... Cluster (all database files) should be backed up to some external place and WAL files should be copied (archived) to some external place either.

Actually, the primary task of Patroni - implement automatic failover and some other tasks around it, i.e.: manual failover, cascading replication, provide health-check for haproxy or any other load balancer, provide possibility to reconfigure all nodes of the postgres cluster and so on. Backup&recovery is not something what Patroni could solve for you.

It's not an easy task to implement backup&recovery 100% right. Instead of inventing your own bicycle just use something already exists and proven to work, for example [wal-e](https://github.com/wal-e/wal-e), [pgbarman](http://www.pgbarman.org/) or [pgBackRest ](https://github.com/pgbackrest/pgbackrest). There you can configure your backup&retention policy, i.e. how long your backups and WAL files should be stored. It also will take care about removing old (unneeded) files. But in any case, all these backup&WAL files should not be stored neither on master nor on any replicas.

Actually it is not

**Comment by ovidiucp** [comment]
I agree, using something external makes more sense.

I was using the configuration files provided by patroni (see [postgres0.yml](https://github.com/zalando/patroni/blob/master/postgres0.yml)) with few modifications for my Kubernetes setup. I now changed `archive_mode` to `off`, and changed `archive_command` to `/bin/true`.

Perhaps the default configuration files should comment out those lines to avoid future issues.

**Comment by CyberDem0n** [comment]
Changed sample config files with https://github.com/zalando/patroni/pull/265
