### ISSUE TITLE
demote replication

### ISSUE THREAD

**Issue by killerwzb** [zalando/patroni#2658]
### What happened?

Enabling dcs_ failsafe mode, if the DCS fails and there is a synchronous replication relationship in the current cluster, does it support demoting synchronous replication to asynchronous replication to avoid problems with the postgres on the standby cause the primary hang.

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### What did you expect to happen?

n/a

### Patroni/PostgreSQL/DCS version

-   Patroni version:  3.0.2
-   PostgreSQL version: 14.5
-   DCS (and its version): etcd 3.0

### Patroni configuration file

```yaml
n/a
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by CyberDem0n** [comment]
No, when removing nodes from synchronous_standby_names they have to be removed from DCS first.
Otherwise we get a situation that the node is counted as synchronous according to information stored in DCS and be promoted while in fact it was asynchronous.

And for the future, please ask questions on Slack.
