### ISSUE TITLE
More verbose (debug) logging

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/patroni#270]
To troubleshoot issues, it would be useful to have more debug logging available.

This requires a mechanism to enable it (environment variable for example), but also more logging statements in general.

**Comment by offmindby** [comment]
+1

**Comment by maksym** [comment]
+1

**Comment by wilfriedroset** [comment]
I think this is not needed anymore 🤔

You can set the logging level using two ways since at least [1.5.4](https://github.com/zalando/patroni/blob/master/docs/releases.rst#version-154):
* using [YAML Configuration file](https://patroni.readthedocs.io/en/latest/SETTINGS.html?highlight=debug)
* using [Environment Configuration](https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html?highlight=LOG)

If you are using systemd to manage patroni, you can use drop-in configuration file to enable debug logs

```
# cat /etc/systemd/system/patroni.service.d/debug.conf
[Service]
Environment="PATRONI_LOGLEVEL=DEBUG"
```

After adding the file, don't forget to reload systemd manager configuration using `systemctl daemon-reload`, then reload or restart patroni to take the environment into account. More over a lot of debug logs have been added since 2017 (over the last 2 years).

Feel free to close or clarify what types of debug messages would be useful for you 👍
I'm sure this would be deeply appreciate

**Comment by alexz0nder** [comment]
I prefer to use yaml-file because I have written a Docker to bring up a cluster node and entrypoint of which get secrets from our Vault service.
So, could someone please describe in more detail how to use logging parameters with YAML Config file? Because I can't find any example of logging part of patroni.yml on the Internet.

**Comment by CyberDem0n** [comment]
@alexz0nder you can define the log section in the config.yaml: https://patroni.readthedocs.io/en/latest/SETTINGS.html#log

**Comment by MustafaAshraf10** [comment]
> @alexz0nder you can define the log section in the config.yaml: https://patroni.readthedocs.io/en/latest/SETTINGS.html#log

the link is not working

**Comment by vxjohanforssell** [comment]
See https://patroni.readthedocs.io/en/latest/yaml_configuration.html#log
