### ISSUE TITLE
Kubernetes setup

### ISSUE THREAD

**Issue by Mahaswami** [zalando/patroni#278]
I am looking for starting points of installing Patroni in Kubernetes and AWS in particular. Appreciate some steps as starting point.

**Comment by alexeyklyukin** [comment]
We don't have a tutorial at the moment, but if you already know your way around K8S take a look at the  Spilo Docker image https://github.com/zalando/spilo/tree/master/postgres-appliance.

One you build the image, the yaml manifest in this repo should get you up and running with K8S on top of GCE. It requires you to create the GCS bucket in advance and have a running Etcd. This manifest doesn't support K8S on top of AWS yet, but you can change WAL_GSC_BUCKET to WAL_S3_BUCKET (and of course, create the S3 bucket first) and see how far would it get you. It also relies on Petsets and VolumeClaimTemplates, so you need recent K8s installation. 

We are working on Helm packages for Spilo, but initially AWS on K8S is also out of scope there.

**Comment by ram-argus** [comment]
Hi Alex, thanks for sharing this,
For the backup storage, is there a way to just use a local folder?
If we use k8s volume-mount to a directory instead of a specific bucket we can allow k8s to abstract the actual volume used (can still use gce/s3 buckets, but also all other volume-backends k8s supports) and avoid the cloud-vendor dependency altogether.

**Comment by ram-argus** [comment]
also, using supervisord to run all processes in the same container is against the best practice of using a [single process per container](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run-only-one-process-per-container). running thinds together in k8s is super easy with pods.

from k8s 1.4, you can use [cron-job](https://github.com/kubernetes/kubernetes/issues/2156), and the pgq can probably run in the same pod but in a separate container.

**Comment by alexeyklyukin** [comment]
Hi @ram-argus,

I don't see a way to abstract a bucket on S3 or GSC using volume mounts (at least according to the http://kubernetes.io/docs/user-guide/volumes/), do you have a link to any documentation describing this?

Also, WAL-E, the WAL archiving and backup solution that we use right now does not support plain folders: https://github.com/wal-e/wal-e

It would be possible to add a logic to try to backup and archive to a local folder if neither GCS nor S3 variables are set, but that would require changes to the Docker container, since currently we rely on WAL-E (pull requests are welcome).

As for replacing supervisord, the current Spilo image should work for both K8S and a weird setup of our own, where we are allowed to run only a single container per EC2 instance. I think the way to go would be to separate the K8S image into a separate project and take advantage of scheduled jobs and multiple containers per pod.

**Comment by jchauncey** [comment]
@alexeyklyukin do you guys have a chart yet for htis? even if it only works on GCS? I want to try and run thsi on AWS but would love to take advantage of what you guys have already done.

**Comment by jchauncey** [comment]
Nevermind found the chart - https://github.com/kubernetes/charts/tree/master/incubator/patroni
