### ISSUE TITLE
Add HAProxy autoconfiguration

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#28]
In a multi-replica environment, HAProxy needs to be configured and updated with the correct current master and replicas.  Add a method to update haproxy.cfg with this information.

How I imagine this working is a separate, smaller daemon which monitors for changes of master and updates haproxy.cfg on the haproxy server(s).

**Comment by jankeirse** [comment]
I have just published a little tool that should be able to do this: https://github.com/TVHGroup/pc4patroni
It is in alpha state right now, feedback is very welcome.

**Comment by alexeyklyukin** [comment]
H @jankeirse i, thanks for sharing your tool. You can actually get notifications from etcd of a key change using the watch functionality, i.e. look at https://github.com/zalando/patroni/blob/master/patroni/etcd.py.

Additionally, did you try to use patroni callbacks, especially on-role-chag?. It requires you to run your script that modifies the configuration from the same host patroni runs at, which might be not what you want, but it has an advantage of being DCS-independent, not tied to etcd or Zookeeper.

Also, instead of asking the etcd, you can query patroni itself (using the REST API), i.e. /master or /slave endpoints in order to find out if the master information stored in the proxy is the same as the one returned by the endpoint (and do some actions depending on the outcome). By talking to Patroni you can avoid dependency on the specific DCS.

**Comment by jankeirse** [comment]
Thanks for your feedback @alexeyklyukin, I am aware of the watch functionality but didn't get it working and had to get it up and running so I chose the current solution until I find the time to figure out why the watch didn't work. I'd also have to change the setup (either make the script multi threaded or sacrifice the current capability of one node serving/watching multiple clusters which probably doesn't make that much sense anyway and was only added because in the current design it was not really extra work.) 
I must have missed the callback capability, I guess that could probably be used in combination with key based SSH login to the proxy machine. However the current implementation also has an advantage: you can have many proxies and the actual cluster nodes don't have to know about them. 
The reason why I chose to query the DCS instead of the API was that it makes the tool much simpler: all you need to do is connect to the DCS. If I were to connect to want to connect to the REST API, AFAIK I'd have to implement a system that can query various nodes to find one that is alive, implement timeouts if connection to a node fails,... In the current setup, all this complexity is handled by the DCS library of choice (and since I am importing the relevant classes from the patroni code, adding another one shouldn't take more than an hour or so.)

**Comment by jankeirse** [comment]
Would it be a good idea to link to Spilo, patroni-compose and my tool at the end of the Getting Started section of the current README.md? As most users will not use Patroni on it's own it might be worthwhile to list the currently existing options.

**Comment by jberkus** [comment]
I'm rebuilding patroni-compose based on Kubernetes; expect something next week.  I'll be slurping in the HAProxy as well.

**Comment by CyberDem0n** [comment]
I think pr#225 should solve this issue. Example in the pull request covers only etcd case, but it should work as well for zookeeper and consul.

**Comment by LappleApple** [comment]
@CyberDem0n @jberkus @alexeyklyukin @jankeirse Did PR #225 solve the issue? :)

**Comment by alexeyklyukin** [comment]
I think so. Please, reopen it if it didn't solve the issue for you.
