### ISSUE TITLE
Callback for custom operations after initial bootstrap

### ISSUE THREAD

**Issue by zenitraM** [zalando/patroni#291]
Our usecase involves creating a lot of database clusters that need to have some initial database setup (some specific databases with extensions) created on the cluster (so, only once after the initial initdb bootstrapping) before becoming usable.

So we would like to have a way for Patroni to invoke the running of these tasks after the db is created but before the node is deemed ready. 

I was thinking on adding a new `on_bootstrap` hook that gets executed after the initial bootstrap currently done [here](https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L973) and blocks until completion. 

Would this make sense?, can you think of any other way to achieve this?

**Comment by CyberDem0n** [comment]
> I was thinking on adding a new on_bootstrap hook that gets executed after the initial bootstrap currently done here and blocks until completion. 

Since there is already `bootstrap` section in the configuration file, probably something like (see below) would be better than `on_bootstrap`
```yaml
bootstrap:
  post_init: /your/script/or/binary
```

Patroni should run this executable and pass connection string as an argument. I think this step should be done right after starting up freshly initialized cluster: [patroni/postgresql.py#L975](https://github.com/zalando/patroni/blob/39d16fe2f95c87793a9227f6c32f2d0953a057b7/patroni/postgresql.py#L975), but before creation of all kind of additional users and roles.

**Comment by zenitraM** [comment]
Ok, we're going to work on adding it that way then.

Wouldn't it make sense to execute it _after_ the creation of roles? - so then we can pass the superuser info in the connection string.

**Comment by CyberDem0n** [comment]
> so then we can pass the superuser info in the connection string.

Superuser is created by initdb.

Please never pass password in the connection string. It has to be written into file with the permissions 0600 and filename should be exported as environment variable `PGPASSFILE`. This way any application using `libpq` will be able to "catch" it.
You can take [create_replica](https://github.com/zalando/patroni/blob/master/patroni/postgresql.py#L415) method as an example.
