### ISSUE TITLE
Allow to set "authentication" from DCS

### ISSUE THREAD

**Issue by zenitraM** [zalando/patroni#294]
We've been thinking about setting the authentication parameters (replication/superuser) on the bootstrap section for them to be propagated over the DCS instead of having to coordinate their distribution to all nodes.

However, it seems that the `authentication` key from the dynamic configuration is ignored explicitly here:
https://github.com/zalando/patroni/blob/master/patroni/config.py#L172

Is there any reason for that?

**Comment by CyberDem0n** [comment]
Originally there were replication username and password in the connection string in DCS, but we decided to get rid from them in order to be secure.

DCS can be accessed by different application and users and they are able to read any keys from there.
We are against giving superuser access to everybody. Having of replication credentials is nearly the same as having superuser, because it gives you permission to fetch all database files...
Sure, in some cases it is possible to configure authentication for DCS, but Patroni doesn't support it yet.
In any case you will have to distribute logins/passwords (and/or certificates) in a secure way, either for DCS or for superuser/replication.

**Comment by zenitraM** [comment]
We wanted to do that for testing only but you're right, I guess it's a better approach to be safe by default than sorry. Thanks!
