### ISSUE TITLE
Two site / two cluster config

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#310]
Hello,

A common use case which I currently implement often is as follows:

Site A:
 - node A1
 - node A2
 - node A3

Site D (DR site):
 - node D1
 - node D2
 - node D3

Site A would be configured as a normal Patroni cluster.

Site D would be configured as a master-less cluster with D1 attached to A(master) and D2 and D3 cascading to D1.

Ideally I would actually have D2 and D3 replicating from D(lock owner which wasn't a master) - but I don't have this today.

Is there a way to do this in Patroni, or can anyone suggest somewhere I could concentrate some effort to make it work?

The requirements are:

- Two 'sites' A/D
- A is fully protected by automatic failover within site, but not between sites (manual failover to D only)
- D has no master under normal operation, with one node connected to A and the other two nodes cascading
- Failover to D is a single command, which brings up a node as master (and removes the cascading links if needed)

Cheers,
James

**Comment by CyberDem0n** [comment]
> Site D would be configured as a master-less cluster with D1 attached to A(master) and D2 and D3 cascading to D1.

> Ideally I would actually have D2 and D3 replicating from D(lock owner which wasn't a master) - but I don't have this today.

Hi,

 1. It's possible to exclude node from automatic/manual failover with `nofailover: true` tag
 2. There is also `replicatefrom: node_name` tag available, which makes it possible to configure cascading replication. If the `node_name` is not available Patroni will get back to the leader to replicate from.

Using these two tags you can configure your 'Site D' as you want.
Failover with the single command is a little bit an issue, because of 'nofailover' tag. Neither `patronictl failover` nor `POST /failover` to the REST API will work, but, there are to solutions for that:
 1. You can create `/service/<cluster_name>/failover` key in DCS (user any available tooling for that) with the value `{"candidate": "D1"}`. Patroni on the Node D1 will accept it and promote.
 2. You can ssh on the D1 and run `pg_ctl -D <data_directory> promote`. Patroni will figure out that postgres is running as a master and take the leader key

**Comment by jamessewell** [comment]
That looks perfect.

One initial question:

Would I need to clear the replicatefrom tags after promotion? 

I'll do some testing as well - thanks for the reply!

Cheers,

**Comment by CyberDem0n** [comment]
> Would I need to clear the replicatefrom tags after promotion? 

`replicatefrom` is not that important in this case, it would be better to remove `nofailover` tags from all the nodes on the Site D (to enable automatic failover).
It's possible to do it without restarting of Patroni, just update configs and send SIGHUP to the patroni process or do 'POST /reload' on the REST API.

It looks like  be we need to implement `patronictl reload`...

**Comment by jamessewell** [comment]
So if we have D1, D2, D3.

- D1 replicating from A
- D2 and D3 are cascading.

If I remove the **nofailover** tags and D3 gets the leader lock would that mean D2 would still cascade to D1 (which would attach to D3)?

Cheers,

**Comment by CyberDem0n** [comment]
> If I remove the nofailover tags and D3 gets the leader lock would that mean D2 would still cascade to D1 (which would attach to D3)?

Correct. But you have all the controls in your hands, so you can remove 'nofailover' as well.

**Comment by jamessewell** [comment]
Sounds reasonable - thanks for the help.

**Comment by dtseiler** [comment]
@jamessewell I'm looking to do this same thing. I'm still feeling my way through patroni now but wondering if you have any info or concrete examples that you'd feel comfortable sharing.
