### ISSUE TITLE
Postgres is stuck in boot up sequence

### ISSUE THREAD

**Issue by maorvnera** [zalando/patroni#317]
2016-09-20 13:03:43,803 INFO: establishing a new patroni connection to the postgres cluster
FATAL:  the database system is starting up

```
LOG:  invalid resource manager ID 114 at 0/443245C0
cp: cannot stat '/var/lib/postgresql/wal_archive/0000000C.history': No such file or directory
FATAL:  the database system is starting up
.FATAL:  the database system is starting up
.FATAL:  the database system is starting up
.FATAL:  the database system is starting up
.FATAL:  the database system is starting up

```

Configured patroni/postgres to not use WAL archiving...
Seems like stuck forever... 
only thing that helped is deleting data dir manually and allowing to resync

**Comment by alexeyklyukin** [comment]
You can  do patronictl reinit instead of deleting the data directory manually

The message from cp you've shown tells that there is no history file in the wal_archive. This could be a normal error message, since PostgreSQL checks for the next history file to detect the case of the master's failover.

As for the FATAL message - my bet is that PostgreSQL tries to get a WAL segment and fails. If you still can reproduce it - please, reopen this issue and show us the log from the stuck replica.
