### ISSUE TITLE
Patroni does not detect extremely stale replicas

### ISSUE THREAD

**Issue by trifthen** [zalando/patroni#325]
In the event a replica is very far behind, several of these errors will appear in the Postgres logs upon starting Patroni:

    FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000005000000000000001B has already been removed

In the case a replica can not catch up to the primary node, Patroni should stop the replica and either rebuild the node, or quit attempting to rejoin the cluster.

**Comment by ants** [comment]
Detecting this reliably is the hard part. I don't think there is any other way to detect this externally besides parsing PostgreSQL logs. Parsing logs is a huge can of worms because the logs might go into files in arbitrary location, stderr or syslog. I think it's also possible to get these messages when a streaming host falls too far behind, then switches over to pulling from the archive, switching back to streaming once it has caught up.

A thought I had was to have a small proxy daemon that speaks PostgreSQL replication protocol, the database would then connect locally to this daemon and would get proxied to the correct master. The proxy can then forward relevant error messages to Patroni and can also be used to change primary_conninfo without restarting the standby. I have actually written one that does the proxying part and could be extended to publish the error information.

Another idea is to make Patroni expose xlog dir contents over the API. If a standby is not able to connect to master Patroni could then compare recovery point on standby to xlog available on the master to determine if it has fallen hopelessly behind and should reinit. There are a bunch of nuances about how to figure the recovery point out when you can't connect to the standby because it hasn't reached consistent recovery point yet.

And to top this all off, if archiving is enabled you would need a way to poll the archive to see if recovery is still feasible.

Seems like a whole bunch of work complicated work for something that is reasonably well solved by monitoring for replication lag and having an admin manually poke Patroni to reinit if it seems the right way to solve the issue. Reinit is not always the correct option anyway, you want to avoid reiniting a terabyte database if you can avoid it by using rsync. And having the standby give up buys little else besides a reduction in log spam.

**Comment by trifthen** [comment]
For what it's worth, Patroni is perfectly positioned to monitor replication lag on its own. The commonly used method is to use `pg_current_xlog_location` on the primary, `pg_last_xlog_replay_location` on the replica, and `pg_xlog_location_diff` for the total lag. Shouldn't there be an option to drop replicas from the cluster if their lag gets too high?

**Comment by ants** [comment]
Patroni already monitors replication lag to make sure stale replicas don't get promoted. Dropping is a different issue. Why would someone want to drop a stale replica from cluster and what would it entail? The best that Patroni could do is to shut the server down to avoid wasting resources. For a completely automated cloud one would want a higher level supervisor that determines that one server is unhealthy, adds a new server and removes the unhealthy server. Something like Kubernetes.

**Comment by trifthen** [comment]
I'm not sure I agree, but it's clear this isn't going anywhere.
