### ISSUE TITLE
Patronictl reports incorrect lag during failover

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando/patroni#342]
> +-----------------------+------------+----------------+--------+----------+-----------+
> | Cluster               | Member     | Host           | Leader |  State   | Lag in MB |
> +-----------------------+------------+----------------+--------+----------+-----------+
> | test | i_3365f78e | 172.31.136.227 |        | starting |    779488 |
> | test | i_8cceeb30 | 172.31.145.161 |   \*    | running  |         0 |
> | test | i_c70e9d7a | 172.31.137.53  |        | stopped  |    779488 |
> +-----------------------+------------+----------------+--------+----------+-----------+

A note to myself to investigate

**Comment by ainlolcat** [comment]
Not sure if it is same issue but patroni calculates lag between current node and master based on current xlog position or 0.  If postgres is starting up or down lag is master xlog position - 0 == DB size. In most cases it is inconvenient only for human eyes because postges will start and lag will be calculated correctly. Only problem if db size less than maximum_lag_on_failover.

**Comment by CyberDem0n** [comment]
Fixed in https://github.com/zalando/patroni/pull/567/commits/ac3669cfc0fc27763c4c893595bd7cfae9ff9116
