### ISSUE TITLE
Add simple HTTP check for "is master"

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#46]
We need a simple HTTP check for HAProxy load balancing (and others) which checks if the server whose API is queried is currently the master, without parsing JSON, using a URL like <server>/ismaster/.   This will allow using http-check expect in HAProxy to determine the master.

Make sense?

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/blob/master/patroni/api.py#L48
This line is a a bit cryptic, but...
Currently any URL which contains "master" will return status_code=200 if `not pg_is_in_recovery()` otherwise it will return status_code=503.
The same works for any other roles. For example /is_slave/ (didn't changed role name yet) will return 200 if  `ps_is_in_recovery()`.
HAProxy can use  `/ismaster/`, or even `/` in order to determine who is the `master`

**Comment by jberkus** [comment]
Hmmm.  I'm not sure that line of code will survive adding more stuff to the API .... will need something more specific.
