### ISSUE TITLE
Add new commands to API

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#47]
We need the following commands in the API to support manual failover and other reasonable operations:

* shutdown
* promote
* restart
* reinitialize

This will require adding new paths to the API.  Given that, do we want to stick with SimpleHTTPServer?

**Comment by CyberDem0n** [comment]
Adding of a new endpoints to the API is absolutely not a problem. Together with SSL and Basic-Auth support I've implemented simple routing mechanism. Original python module was routing all GET requests to `do_GET` method, POST requests to `do_POST` method and so on. The new routing is a little bit smarter:
`GET /foo/bar` request will call `do_GET_foo` method.

For us this means that we just need to implement bunch of new methods:
```python
    @check_auth
    def do_POST_shutdown(self):
        """handler for `POST /shutdown` request"""

    @check_auth
    def do_POST_promote(self):
        """handler for `POST /promote` request"""
```

`@check_auth` decorator is taking care about authorisation for a given endpoint.

The most hardest task is actually implementing needed functionality, because most of it must be executed from the main loop or at least any of them are affection decision tree...

And I have some questions about operations:
* shutdown -- it should just shutdown postgres. Am I correct? Should the`member` key in a configuration store still be maintained?
* start -- if we have `shutdown` probably we need start as well.
* restart -- is it allowed on master? Probably yes, because restart is faster then failover.
* reinitialize -- I hope this is something which can be triggered only on replicas?

**Comment by jberkus** [comment]
> The most hardest task is actually implementing needed functionality, because most of it must be executed from the main loop or at least any of them are affection decision tree...

Wait, what?  Explain?

>    shutdown -- it should just shutdown postgres. Am I correct? Should themember key in a configuration store still be maintained?

I was planning on having it shut down the whole server, including Patroni.  This is just meant as a STONITH method; having the possibility that 


    restart -- is it allowed on master? Probably yes, because restart is faster then failover.
    reinitialize -- I hope this is something which can be triggered only on replicas?

**Comment by jberkus** [comment]
Feh, damn browser reload.  I was saying: 

>    shutdown -- it should just shutdown postgres. Am I correct? Should themember key in a configuration store still be maintained?
>    start -- if we have shutdown probably we need start as well.

I was thinking of shutdown as pure STONITH: it shuts down Postgres AND Patroni.  While I can see the utility of having both remote startup and shutdown, I'm a bit concerned about breaking the link of "Patroni is running therefore Postgres is running".  

> restart -- is it allowed on master? Probably yes, because restart is faster then failover.

Yes.  The reason for restart is that you want to load new configuration, pretty much.

> reinitialize -- I hope this is something which can be triggered only on replicas?

Well, I'm not sure about that.  One of the reasons to run re-initialize is that you messed up during setup and want to rebuild the DB, when there is only one server in the cluster right now.  So I think a good rule would be "only replicas, OR the master if there are no replicas".

**Comment by CyberDem0n** [comment]
> Wait, what? Explain?

For example if we are doing "reinitialize" or "restart", we should not run usual decision tree, because Patroni will notice that Postgres is not running and will try to start it in read-only mode.

>  I'm a bit concerned about breaking the link of "Patroni is running therefore Postgres is running". 

It is not always the case. Patroni starts first and only then it is starting up Postgres. And actually Postgres may already be running even before Patroni has started.

> So I think a good rule would be "only replicas, OR the master if there are no replicas".

Hmm, so hypothetically we provide easy interface to "destroy" cluster... Think about usual setup, one master + one replica and the replica has failed for some reason. If somebody accidently will try to "reinitialize" master instead of replica he will destroy everything...

If I understand you correctly you are trying to find the solution for the case when you are messed up with configuration and Postgres didn't started but initialize key remains in a configuration store forever. It will make impossible to "bootstrap" cluster with the same name once again. I guess "patroni-cli" should allow to create/remove arbitrary keys in a configuration store. Removal of keys is not really dangerous and the healthy cluster can survive it even without restarting in read-only. Basically healthy cluster will "restore" all keys in a few seconds.

**Comment by jberkus** [comment]
> For example if we are doing "reinitialize" or "restart", we should not run usual decision tree, because Patroni will notice that Postgres is not running and will try to start it in read-only mode.

Hmmmm.  Is it possible for those operations to actually get interrupted by a separate Patroni thread?

> It is not always the case. Patroni starts first and only then it is starting up Postgres. And actually Postgres may already be running even before Patroni has started.

Again, it depends on what you're trying to accomplish; my thinking was to use "shutdown" for STONITH.  The simplest way to do this is to have a shutdown command which shuts down postgres and patroni.  If having a general start/stop is useful, then we'll need to also add a value to the SIS key for the server which is "donotstart", and gets checked by Patroni.  Seems reasonable enough.

> If I understand you correctly you are trying to find the solution for the case when you are messed up with configuration and Postgres didn't started but initialize key remains in a configuration store forever. It will make impossible to "bootstrap" cluster with the same name once again. I guess "patroni-cli" should allow to create/remove arbitrary keys in a configuration store. Removal of keys is not really dangerous and the healthy cluster can survive it even without restarting in read-only. Basically healthy cluster will "restore" all keys in a few seconds.

Hmmm.  I'm not sure I want to go there with the CLI; it seems like encouraging people to edit keys by hand, and that's not such a good idea.  Heck, they can do that anyway with curl. For now, let's just make it so that reinitialize only works on replicas.

**Comment by CyberDem0n** [comment]
https://github.com/zalando/patroni/pull/51 implements restart and reinitialize via API

**Comment by LappleApple** [comment]
In light of PR #51, can we close this issue @CyberDem0n + @jberkus?

**Comment by CyberDem0n** [comment]
From the above list only shutdown is not there and I'm not sure that it is really needed. Closing it.
