### ISSUE TITLE
Question: how to apply pending config updates to a cluster?

### ISSUE THREAD

**Issue by makeittotop** [zalando/patroni#485]
This is a question rather than an issue.  

Let's say I've got a master and 2 standbys. 

What is the recommended way to apply pending configuration changes to a cluster so as to cause  minimum disruption to the availability of its service?

For example, should hitting the API endpoint http://<ip>:8008/restart in the following order be good enough -
 * restart standby 1
 * restart standby 2
 * failover from the master to either standby 1 or 2 
 * restart the now former master (now standby) 

If there is another preferred way (documented or otherwise), please let me know.

**Comment by alexeyklyukin** [comment]
@makeittotop your plan looks good to me. Note that you can use both scheduled restarts and scheduled failovers in order to schedule Patroni to do restarts and failovers at the time when the disruption to your service is minimal. It's easier to do with ``patronictl``, although also possible with the REST API.

**Comment by CyberDem0n** [comment]
It also depends on your setup.
If you are using haproxy or something similar (ELB for example)  for traffic routing, it will take for them some time (up to 10 seconds) to figure out that master now runs on a different node. 
In this case it's better to just restart postgres master instead of doing failover.

**Comment by makeittotop** [comment]
@Oleksii Thanks for the comment.

Do you simply mean the patroni service restart when you say "Scheduled
restart"?

**Comment by alexeyklyukin** [comment]
No, not Patroni service. Patroni has a feature that allows to schedule the restart of the PostgreSQL database it manages some time in the future. It is supported with either ``patronictl`` tool or the REST API. Same for the failover.

**Comment by makeittotop** [comment]
I only know about patronictl failover <cluster-name>

Can you please tell me the subcommand for it or point to a doc?

Thanks!

**Comment by alexeyklyukin** [comment]
Just run patronictl failover in interactive mode. It will ask you when would you like to do the failover.

**Comment by makeittotop** [comment]
Sweet! Will try that. Thanks guys!
