### ISSUE TITLE
haproxy cant connect to patroni

### ISSUE THREAD

**Issue by MilesBrown** [zalando/patroni#512]
Hi dear CyberDem0n.
I run patroni cluster and connecting to the cluster using psql and 5432 port , but when I install haproxy and change configuration I cant connect to patroni through haproxy port. Here is the config and tests : 
https://pastebin.com/0ZG27sjQ

And also one more question , when  I'm trying to reinit my broken cluster with patronictl have some etcd errors : https://pastebin.com/J2HFkh1m I have same errors on other patronictl functions also.
etcd config : 
```
etcd --name pg2 --initial-advertise-peer-urls http://10.80.80.196:2380 \
  --listen-peer-urls http://10.80.80.196:2380 \
  --listen-client-urls http://10.80.80.196:2379,http://127.0.0.1:2379 \
  --advertise-client-urls http://10.80.80.196:2379 \
  --initial-cluster-token etcd-cluster-1 \
  --initial-cluster pg1=http://10.80.80.195:2380,pg2=http://10.80.80.196:2380,pg3=http://10.80.80.197:2380 \
  --initial-cluster-state new --heartbeat-interval 250 --election-timeout 1250
```
When I delete manually data folder and start patroni it starts in slave mode ,but there is human risk to delete production folder like gitlab guys do :)
What I'm doing wrong ? Please help me .

With best regards.

**Comment by CyberDem0n** [comment]
> I cant connect to patroni through haproxy port. 

What is in haproxy log?

> when I'm trying to reinit my broken cluster with patronictl have some etcd errors
bash-4.2$ patronictl reinit cluster2
Error: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, zookeeper, exhibitor, etcd'

you didn't specified:
1. configuration file for patronictl.
2. name of the node you want to reinitialize (Well, in your case you kind of specified a node name, but didn't specified the cluster name. It wasn't easy to figure it out, because you are using very confusing names for nodes: cluster1 and cluster2)

the right command would be: `$ patronictl -c /etc/patroni/postgres0.yml reinit pg1 cluster2`

**Comment by MilesBrown** [comment]
thanks for patronictl command now it works.
In ha proxy log there is no any error : 
```
[root@localhost log]# cat haproxy.log 
Aug 30 10:05:21 localhost haproxy[13181]: Connect from 10.80.80.195:52644 to 10.80.80.195:5000 (ft_postgresql/TCP)
```

**Comment by MilesBrown** [comment]
Thank you for your answer, I solve problem with haproxy with upgrade to newer version

**Comment by MilesBrown** [comment]
One more question in my postgresql.conf I have this configuration 
```
[root@localhost data]# cat postgresql.conf 
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

data_directory = '/var/lib/pgsql/9.6/data/'
hba_file = '/var/lib/pgsql/9.6/data/pg_hba.conf'
ident_file = '/var/lib/pgsql/9.6/data/pg_ident.conf'
archive_command = 'mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f'
archive_mode = 'on'
archive_timeout = '1800s'
cluster_name = 'pg1'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '5'
max_wal_senders = '5'
max_worker_processes = '8'
port = '5432'
track_commit_timestamp = 'off'
unix_socket_directories = '.'
wal_keep_segments = '8'
wal_level = 'replica'
wal_log_hints = 'on'
```
include 'postgresql.base.conf' (old main config) mean that if I have for example autovacuum on in base.conf patroni will use it also ? Or I must directly add it to patroni template ?

**Comment by CyberDem0n** [comment]
In most cases your goal is to have similar configuration on all nodes, therefore instead of editing config files everywhere it's better to use [dynamic configuration](https://github.com/zalando/patroni/blob/master/docs/dynamic_configuration.rst).

Also from your logs I've noticed that you are still using version 1.2.5, but if you update to 1.3.3, you will be able to use `patronictl show-config` -- to show dynamic configuration and `patronictl edit-config` -- to change it.
