### ISSUE TITLE
Add support for multiple Etcd endpoints

### ISSUE THREAD

**Issue by davissp14** [zalando/patroni#523]
Looking at the docs specified here, it appears we can only specify a single Etcd endpoint.
https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html#environment

The limitation here is that if that specific endpoint is not available on start-up, it's obviously not going to be able to auto-discover the other members to establish a connection.  Seems we could avoid this issue by allowing users to manually specify each member endpoint or each proxy endpoint they have available.  Patroni could then cycle through the endpoints until it is able to establish a connection.

**Comment by alexeyklyukin** [comment]
You can point Patroni to either A or SRV records containing multiple endpoints, Patroni will cycle through them to find one it can connect to.

**Comment by davissp14** [comment]
How would you go about specifying multiple internal ips inside a private network?

**Comment by alexeyklyukin** [comment]
Same way. Actually our use-case is mostly DNS-based discovery, we don't use static initial cluster addresses. The latter is error-prone and doesn't play well with dynamic hosts (i.e. in he cloud), since the addresses are not known in advance. YMMV.

**Comment by davissp14** [comment]
Interesting, our initial cluster addresses are known prior to start-up.  In the event a node need to be moved onto a new host, our environments are updated accordingly.  If the endpoints are only used to establish the initial connection and are read from the configuration file, it seems as long as we keep this file is updated when changes are made it shouldn't be an issue, right?

SRV records may be a sane approach, it's not really something we are prepared to use in the near term.  The endpoint cycling on failure sounds like something that's already happening, is multiple endpoint support within the config, something you guys would consider supporting?

**Comment by CyberDem0n** [comment]
@davissp14, Patroni needs to know only one host from etcd cluster.

Every etcd node can report etcd cluster topology via  `/v2/machines` REST API call, and Patroni is using it: https://github.com/zalando/patroni/blob/master/patroni/dcs/etcd.py#L124

If one of the requests to etcd failed, Patroni switches to another etcd node, re-executing request and refreshes topology of etcd cluster.
In addition to that Patroni also doing it (refreshes etcd cluster topology) periodically, every 5 minutes.
If you move one of etcd node to another host and another ip, Patroni will discover it maximum in 5 minutes.

Why did we choose a 5 minutes? Because it nearly impossible to move all etcd nodes to a different ips/hosts.

And at the end we can return to your original question.
Yes, we can make it possible to specify multiple etcd hosts in the configuration, but how it should behave later, if for some reason all etcd nodes will become not accessible?
Should Patroni always retry with the latest topology

**Comment by bradnicholson** [comment]
>Patroni needs to know only one host from etcd cluster.

The main concern here is that if that member is not available when Patroni starts, it won't be able to get a connection to etcd.

**Comment by davissp14** [comment]
> Should Patroni always retry with the latest topology or should it return to original list?

On start-up, the original list would be all that's available, right?

**Comment by CyberDem0n** [comment]
> What would happen if we need to move the Node that's listed in the configuration file?

Update configuration file.

> but wouldn't it result in a disconnect between the runtime configuration and the configuration file?

It definitely would, Config file needs to be changed accordingly. Or better to keep something in configuration file that changes rarely, for example dns name (A or SRV record)

> we would still want the configuration file to represent reality or we would run into trouble when trying to recover from a failure where we would no longer have access to the runtime member cache.

Indeed, config file must be in sync with reality. We are using SRV discovery for that. When etcd cluster chages it's topology, it automatically updates SRV and A records.

It's actually not hard to implement
```yaml
etcd:
  hosts:
    - host1:2379
    - host2:2379
    - host3:2379
```

But you still have to keep this configuration in sync.

**Comment by davissp14** [comment]
> It definitely would, Config file needs to be changed accordingly. Or better to keep something in configuration file that changes rarely

As long as the Etcd cluster meets quorum, Patroni should be able to establish a connection.  There's always going to be the possibility that the single node listed in the configuration file is DOWN, but the cluster is still in a healthy state.  If Patroni is going to offer non SRV / A record connection approaches, allowing users to specify multiple entry points to their cluster seems like a pretty sane ask?

**Comment by CyberDem0n** [comment]
@davissp14 

I think we are talking here about two different issues:
* Initial discovery of etcd cluster nodes
* Access to etcd cluster

It's possible to do initial discovery in multiple ways:
1. Dns discovery, by doing resolve of SRV or A record. We assume that these records are more or less up to date and contain at least on healthy node of etcd cluster.
2. Static discovery by doing an API call to one of nodes of Etcd cluster.
3. Static discovery via multiple nodes. It similar to 2, but if the first node in the list is not accessible, try another one. (not implemented!)

Discovery is only one side of a coin, and actually this step is not always needed. It all depends on the way how we access etcd cluster.

As one could guess, there are more than one way to access etcd cluster.
1. You access every node of etcd cluster directly. In my opinion this is a most widely used and most reliable method of accessing etcd cluster.
2. You access etcd cluster via proxy or load-balancer. Right now it is possible to specify a `etcd.proxy` in a config file and Patroni will not try to discover etcd cluster topology, but always use a given endpoint to connect.
3. Via set of proxies or load-balancers. It is not implemented directly, but still possible, if `etcd.proxy` contains not an IP, but dns name resolved into multiple IP's.

As told before, it's not hard to implement missing parts of discovery and access (3 and 3).
But there is one more missing bit. What should we do if after a long time all endpoints of etcd cluster will become not accessible? If we know that we are connecting via proxy or load-balancer, we should just continue trying. But if we are connecting to all etcd nodes directly, it is getting though, because we need to "re-run" initial discovery:
1. In case if we are relying on A or SRV - resolve them. At Zalando we are using this approach and it is proven to be reliable.
2. With static discovery the only we can do, is to try INITIAL list of etcd nodes provided in the config. Unfortunately there is no guaranty that there is some process (or somebody) keeping all Patroni config files up to date and with really high chance etcd nodes from the config don't exists anymore and therefore Patroni will never reconnect to etcd...

**Comment by alexeyklyukin** [comment]
> With static discovery the only we can do, is to try INITIAL list of etcd nodes provided in the config. Unfortunately there is no guaranty that there is some process (or somebody) keeping  all Patroni config files up to date and with really high chance etcd nodes from the config don't exists anymore and therefore Patroni will never reconnect to etcd...

Currently, if you have only one host used for initial discovery, you have to update the configuration file only when that host is moved. If you specify more than one host there, you'll have to update the configuration file when each of those hosts specified in the configuration file is moved (otherwise, you'll eventually end up with a list of non-existing hosts). In other words, you still need a sync process, but you'll end up doing more work if you sync multiple (presumably all) hosts instead of one. I don't really see any benefits to that.

**Comment by davissp14** [comment]
> As told before, it's not hard to implement missing parts of discovery and access (3 and 3).
But there is one more missing bit. What should we do if after a long time all endpoints of etcd cluster will become not accessible? If we know that we are connecting via proxy or load-balancer, we should just continue trying. But if we are connecting to all etcd nodes directly, it is getting though, because we need to "re-run" initial discovery:

I don't think it's unreasonable to ask users to manage the state of their configuration file if they are entering a static list of addresses.  This should be clearly stated in the documentation.   What does Patroni do when it's unable to connect to the single endpoint after a long time?  Is there any issue in continuing with the existing approach, which I think is error and retry indefinitely?  

> Currently, if you have only one host used for initial discovery, you have to update the configuration file only when that host is moved. If you specify more than one host there, you'll have to update the configuration file when each of those hosts specified in the configuration file is moved (otherwise, you'll eventually end up with a list of non-existing hosts). In other words, you still need a sync process, but you'll end up doing more work if you sync multiple (presumably all) hosts instead of one. I don't really see any benefits to that.

This would only be a problem if you move nodes super often and don't have any automation surrounding this process.

**Comment by alexeyklyukin** [comment]
>This would only be a problem if you move nodes super often and don't have any automation surrounding this process. Also, when you have the ability to provide multiple addresses, it doesn't necessarily mean you have too. If you decide that it's too much work to keep the configuration updated using 3 addresses, just add one. I don't think it makes sense to force infrastructure decisions here.

If you move nodes only infrequently and has an automation in place to change the configuration file, then what's the actual problem we are trying to solve? The issue may happen only if you moved the Etcd node and started a new Patroni cluster after you did so but before the configuration has been changed, presumably a short interval of time. That may happen if you are running something like a DB as a service at a scale with a single template for Patroni that contains your Etcd address, but for that use case one can maintain at least a list A records with the same name pointing to different Etcd addresses, that would already be much better that a list of addresses in the Patroni configuration file.

**Comment by davissp14** [comment]
For what it's worth, I work for Compose and we are a DB as a service company.

> that use case one can maintain at least a list A records with the same name pointing to different Etcd addresses

This comes back to forcing infrastructure decisions, which seems like something Patroni would want to avoid?

> If you move nodes only infrequently and has an automation in place to change the configuration file, then what's the actual problem we are trying to solve? 


Patroni should be mindful of quorum. Just because one node is down, doesn't mean the cluster isn't healthy. 

Say we have a 3 node cluster with nodes A, B, and C.  We add node A to the configuration file.  The host where Node A lies is undergoing maintenance, but Node B and C are alive and well.  The case you're missing is the case where the Node hasn't been moved, but we are still unable to establish a connection.  Make sense?

**Comment by alexeyklyukin** [comment]
Ok, so apparently you fit into the narrow use case when it makes sense :-) Although in your case you would have to both update the etcd topology (in order for the new nodes to discover the existing ones) and Patroni configuration (in order to get the initial topology), binding your automation to Patroni.

I personally don't mind adding more multiple nodes to the etcd host/url parameter.
