### ISSUE TITLE
Failure to startup with existing data directory

### ISSUE THREAD

**Issue by akissa** [zalando/patroni#526]
When started using an existing data directory such as converting a normal postgres server to a cluster the process fails.

It seems patroni checks for the lock owner (No lock and No owner) and then decides to startup as a secondary even though there is no other member in the cluster to pull data from.

This causes a problem because of the options that get written to postgres cause it to fail to start as well.

The process then gets caught in the loop of trying to startup postgres with invalid parameters which continuously fails.

Patroni logs

```
2017-09-21 13:50:39,744 WARNING: Postgresql is not running.
2017-09-21 13:50:39,745 INFO: Lock owner: None; I am backend.home.topdog-software.com
2017-09-21 13:50:39,747 INFO: Lock owner: None; I am backend.home.topdog-software.com
2017-09-21 13:50:39,758 INFO: starting as a secondary
2017-09-21 13:50:39,767 INFO: Lock owner: None; I am backend.home.topdog-software.com
2017-09-21 13:50:39,767 INFO: not healthy enough for leader race
2017-09-21 13:50:39,800 INFO: restarting after failure in progress
2017-09-21 13:50:39,806 INFO: postmaster pid=22214
< 2017-09-21 13:50:39.941 SAST > LOG:  redirecting log output to logging collector process
< 2017-09-21 13:50:39.941 SAST > HINT:  Future log output will appear in directory "pg_log".
2017-09-21 13:50:40,807 ERROR: postmaster is not running
2017-09-21 13:50:40,820 INFO: Lock owner: None; I am backend.home.topdog-software.com
```

Postgres logs

```
< 2017-09-21 13:50:39.942 SAST > WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
< 2017-09-21 13:50:39.942 SAST > HINT:  The database server will regularly poll the pg_xlog subdirectory to check for files placed there.
< 2017-09-21 13:50:39.942 SAST > LOG:  entering standby mode
< 2017-09-21 13:50:39.958 SAST > WARNING:  WAL was generated with wal_level=minimal, data may be missing
< 2017-09-21 13:50:39.958 SAST > HINT:  This happens if you temporarily set wal_level=minimal without taking a new base backup.
< 2017-09-21 13:50:39.958 SAST > FATAL:  hot standby is not possible because wal_level was not set to "replica" or higher on the master server
< 2017-09-21 13:50:39.958 SAST > HINT:  Either set wal_level to "replica" on the master, or turn off hot_standby here.
< 2017-09-21 13:50:39.959 SAST > LOG:  startup process (PID 22216) exited with exit code 1
< 2017-09-21 13:50:39.959 SAST > LOG:  aborting startup due to startup process failure
< 2017-09-21 13:50:39.966 SAST > LOG:  database system is shut down
< 2017-09-21 13:50:50.989 SAST > LOG:  database system was interrupted while in recovery at log time 2017-09-21 13:50:27 SAST
< 2017-09-21 13:50:50.989 SAST > HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
< 2017-09-21 13:50:51.025 SAST > WARNING:  recovery command file "recovery.conf" specified neither primary_conninfo nor restore_command
< 2017-09-21 13:50:51.025 SAST > HINT:  The database server will regularly poll the pg_xlog subdirectory to check for files placed there.
< 2017-09-21 13:50:51.025 SAST > LOG:  entering standby mode
< 2017-09-21 13:50:51.057 SAST > WARNING:  WAL was generated with wal_level=minimal, data may be missing
< 2017-09-21 13:50:51.057 SAST > HINT:  This happens if you temporarily set wal_level=minimal without taking a new base backup.
< 2017-09-21 13:50:51.057 SAST > FATAL:  hot standby is not possible because wal_level was not set to "replica" or higher on the master server
< 2017-09-21 13:50:51.057 SAST > HINT:  Either set wal_level to "replica" on the master, or turn off hot_standby here.
< 2017-09-21 13:50:51.058 SAST > LOG:  startup process (PID 22380) exited with exit code 1
< 2017-09-21 13:50:51.058 SAST > LOG:  aborting startup due to startup process failure
< 2017-09-21 13:50:51.065 SAST > LOG:  database system is shut down

```

**Comment by CyberDem0n** [comment]
> and then decides to startup as a secondary even though there is no other member in the cluster to pull data from.

Patroni always starts postgres in recovery, this is a safety feature. But it seems your case if very-very specific, because you have postgres not running and no initialize key in DCS.

May be it make sense to start postgres as a master right after taking initialize lock.

As a quick workaround I can advise:
1. start postgres manually
2. when postgres is up and running start patroni
3. ask patroni to restart postgres (patronictl restart cluster-name node-name)

**Comment by akissa** [comment]
I think i tried that before but will try again, the issue i remember was that patroni fails to run because it cannot bind to the postgresql port.

Will update after i have followed your workaround steps.

**Comment by CyberDem0n** [comment]
> cannot bind to the postgresql port.

you mean can't connect to the postgres?

Just verify `listen_addresses` and `port` in postgresql.conf and `postgresql.listen` in patroni yaml

**Comment by akissa** [comment]
The workaround works, the challenge is to script it in an automated way. is it possible to use patronictl to init the cluster and then startup patroni after ?

**Comment by akissa** [comment]
@CyberDem0n Thanks for your pointer and help, closing this.

**Comment by tomkcpr** [comment]
Realize this is an older post but have a similar issue with PostgreSQL 10:

`2018-10-30 01:37:00.265 EDT [11371] FATAL:  the database system is starting up
2018-10-30 01:37:00.276 EDT [11373] FATAL:  the database system is starting up
2018-10-30 01:37:00.291 EDT [11370] LOG:  entering standby mode
2018-10-30 01:37:00.292 EDT [11370] WARNING:  WAL was generated with wal_level=minimal, data may be missing
2018-10-30 01:37:00.292 EDT [11370] HINT:  This happens if you temporarily set wal_level=minimal without taking a new base backup.
2018-10-30 01:37:00.292 EDT [11370] FATAL:  hot standby is not possible because wal_level was not set to "replica" or higher on the master server
2018-10-30 01:37:00.292 EDT [11370] HINT:  Either set wal_level to "replica" on the master, or turn off hot_standby here.
2018-10-30 01:37:00.295 EDT [11367] LOG:  startup process (PID 11370) exited with exit code 1
2018-10-30 01:37:00.295 EDT [11367] LOG:  aborting startup due to startup process failure
2018-10-30 01:37:00.296 EDT [11367] LOG:  database system is shut down
`
Trying to start it up manually yields:

`Oct 30 21:56:12 psql03.nix.mds.xyz systemd[1]: Starting PostgreSQL 10 database server...
-- Subject: Unit postgresql-10.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit postgresql-10.service has begun starting up.
Oct 30 21:56:12 psql03.nix.mds.xyz postgresql-10-check-db-dir[28241]: "/var/lib/pgsql/10/data/" is missing or empty.
Oct 30 21:56:12 psql03.nix.mds.xyz postgresql-10-check-db-dir[28241]: Use "/usr/pgsql-10/bin/postgresql-10-setup initdb" to initialize the
Oct 30 21:56:12 psql03.nix.mds.xyz postgresql-10-check-db-dir[28241]: See /usr/share/doc/postgresql10-10.5/README.rpm-dist for more inform
Oct 30 21:56:12 psql03.nix.mds.xyz systemd[1]: postgresql-10.service: control process exited, code=exited status=1
Oct 30 21:56:12 psql03.nix.mds.xyz systemd[1]: Failed to start PostgreSQL 10 database server.
`

Earlier we were getting this:

`2018-10-30 01:26:04.055 EDT [4568] PANIC:  could not locate a valid checkpoint record
2018-10-30 01:26:04.055 EDT [4569] FATAL:  the database system is starting up
2018-10-30 01:26:04.055 EDT [4565] LOG:  startup process (PID 4568) was terminated by signal 6: Aborted
2018-10-30 01:26:04.055 EDT [4565] LOG:  aborting startup due to startup process failure
2018-10-30 01:26:04.056 EDT [4565] LOG:  database system is shut down`

and 

`Oct 30 01:14:25 psql03.nix.mds.xyz patroni[1162]: 2018-10-30 01:14:25,088 ERROR: postmaster is not running
Oct 30 01:14:25 psql03.nix.mds.xyz patroni[1162]: 2018-10-30 01:14:25,107 INFO: Lock owner: postgresql1; I am postgresql2
Oct 30 01:14:25 psql03.nix.mds.xyz patroni[1162]: 2018-10-30 01:14:25,111 INFO: failed to start postgres`

so to fix that we used:

`-bash-4.2$ pg_resetwal /data/patroni -f
Write-ahead log reset
-bash-4.2$`

but that got us into the first error above.  Workaround above hasn't helped even though we set PGDATA in postgress  .bash_profile to /data/patroni.

Would appreciate any hints.

Cheers,
TK

**Comment by tomkcpr** [comment]
Seems solved.  Copied pg_control over from another psql server and restarted.  All three nodes up and running.

Cheers,
TK

**Comment by tigranav** [comment]
I got same error, but in my case problem solved then i removed recovery.conf on first staring node.

**Comment by bdoublet91** [comment]
For patroni 4.0.4, I needed to remove the standby.signal. The Patroni node change from replica RUNNING to leader RUNNING (restart patroni after file deletion).
Also a nice tip of @CyberDem0n, about start postgres in CLI with option in file `postmaster.opts` from /var/lib/postgresql/X/main with patroni stop.
Start patroni, it will detect the postgres and take the lead.
Recover from a failed upgrade with replica wipe datas ...
