### ISSUE TITLE
HA test questions

### ISSUE THREAD

**Issue by jamessewell** [zalando/patroni#546]
Hi, 

I've been running some HA testing with Patroni installed from the RAFT branch (happy to re-test with etcd if needed). 

I'm confused by the following flows:

1. Start three nodes, wait for leader and standbys to boostrap
1. Stop all nodes
1. Start the master node
1. Start the standby nodes
1. Seems like there is a timeline bump every time 

And also:

1. Start three nodes, wait for leader and standbys to boostrap
1. Stop a single standby 
1. Stop the master
1. As expected, no promotion as the standby can't get consensus to take leader
1. Start the master
1. Seems like there is a promotion on the standby and a timeline bump every time 

It seems like the correct behavior here would be to stay on the old master and hold timeline if at all possible.

Cheers,
James

**Comment by CyberDem0n** [comment]
Hi @jamessewell,

this is expected behavior, Patroni always starts postgres in recovery (with recovery.conf), no matter which DCS is used.

There are set of actions needs to be done before promote:
1. Check that you are still allowed to be a master (tags.nofailover == false)
2. Check that your wal position is not far behind the last registered in DCS (pg_current_xlog_location > /optime/leader - maximum_lag_on_failover)
3. Compare your wal position against all other nodes and verify that you not behind any of the others
4. Take leader lock
5. And only if all previous checks succeeded - promote

Without all this checks you can't know that you are allowed to become the master. And actually how do you know that you have need shut down as master? Absence of recovery.conf? It doesn't really work.
If there is no consensus available, Patroni will always create recovery.conf and restart postgres in read-only.

I think timeline bump is not really a big problem, in reality it happens very rare, that your master is dying unexpectedly.

**Comment by jamessewell** [comment]
OK, makes sense
