### ISSUE TITLE
[question] Consul clustering support

### ISSUE THREAD

**Issue by ryanmickler** [zalando/patroni#603]
How well supported is consul? i'm having difficulty trying to get a dockerized set of containers to cluster. I provide `PATRONI_CONSUL_HOST` to each of my three containers, but they each just report that they are master.

**Comment by CyberDem0n** [comment]
Hi,

> How well supported is consul?

As far as I know there are some people/companies running Patroni with Consul in production. I would say it is quite stable.

>  i'm having difficulty trying to get a dockerized set of containers to cluster. I provide PATRONI_CONSUL_HOST to each of my three containers

Have you build your own image or using Spilo? If you are trying to run Spilo with Consul - it will not work. Spilo is only familiar with Etcd, ZooKeeper and Kubernetes API.

There is a one reason why Consul is not supported in Spilo. You have to run a Consul agent in the same container where Patroni and Postgres runs. Upon start this Consul agent have to join some existing Consul cluster. If it fails to join a cluster, it doesn't make much sense even to start Patroni.

> but they each just report that they are master.

Somehow it feels like you are using a Spilo. Since it doesn't support Consul and there is no suitable DCS (etcd, zookeeper) configuration provided from outside, it thinks that container was started locally (testing mode) and decides to start etcd inside the container. Since all etcd are running independently from each other, all nodes are running as masters...
