### ISSUE TITLE
Two questions about switch over

### ISSUE THREAD

**Issue by yangshushu** [zalando/patroni#640]
Hello, I want to ask two questions
1 when the primary down。patroni how to check the primary down and Promote the standby node?
2 In what case patroni will be Switch over?

**Comment by CyberDem0n** [comment]
1. If the primary goes down, replicas will start leader race and one of them will promote (automatic failover). Remaining replicas will start streaming from the new primary. 

2. Switchover - this is when you manually trigger switch of the primary to one of the replicas and bring the old primary as a new replica into the cluster. 
You can do a switchover with the help of patronictl: `patronictl switchover <your-cluster-name>`

It could happen that none of the replicas are eligible to become a new primary, because they all are lagging to match behind the old primary. In this case you can trigger a manual failover with the help of patronictl: `patronictl failover <your-cluster-name>`. It fill ask you a few questions and make the new primary from one of the replicas, but you have to specify what replica must be promoted. This is important.

**Comment by yangshushu** [comment]
Thank you very much for your answer and help, which is very important to me.
I'm going to do a tpcc performance test for Patroni and postgres replication.I want to ask you, what is the suggestion for the patroni parameters.ttl,loop_wait,retry_timeout,maximum_lag_on_failover.
Whether these parameters affect the running of busy database?

There is a possibility to happen switchover in this case?

There is a possibility to happen patroni not able to update value to dcs  in this case?

**Comment by jberkus** [comment]
@yangshushu none of the Patroni parameters should affect performance in any way.  All of those parameters have to do with failure detection and time to switchover.   The defaults are what we recommend for a generic case (otherwise we would change them).  

I don't understand your other two questions, please be more detailed in what you are looking for.

**Comment by CyberDem0n** [comment]
**ttl** - sets when leader key should expire if there are no updates. Default value 30 seconds
**loop_wait** -- how often Patroni should run HA loop. Default value 10 seconds.
**retry_timeout** -- if update of the leader key failed, Patroni will retry it during this time. Default value 10 seconds.
**maximum_lag_on_failover** -- every iteration of HA loop, leader writes into etcd its wal_position. In case of leader race every replica will compare its wal_position with the last registered wal_position of the leader in etcd. If the difference is more than maximum_lag_on_failover, it wont promote.

If Patroni can't communicate with etcd and postgres was running as master, it will restart postgres in read-only.

**Comment by jberkus** [comment]
Closing due to lack of follow-up by OP
