### ISSUE TITLE
pg_basebackup failed, but can't see any error messages about it

### ISSUE THREAD

**Issue by seafoodbuffet** [zalando/patroni#671]
Postgresql 9.4
Patroni 1.4.1 using Consul
master01 has multiple tablespaces, with PG_DATA at /opt/data/psql
and tablespaces at 
/opt/data/tablespace1 through /opt/data/tablespace5

When bootstrapping a replica, we often see pg_basebackup fail, the only thing we see in the patroni log will be this:
```
Apr 29 18:30:23 slave01 patroni[30015]: pg_basebackup: child process exited with error 1
Apr 29 18:30:23 slave01 patroni[30015]: 2018-04-29 18:30:23,502 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Apr 29 18:30:23 slave01 patroni[30015]: 2018-04-29 18:30:23,503 WARNING: Trying again in 5 seconds
```
followed shortly by
```
Apr 29 18:32:43 slave01 patroni[30015]: pg_basebackup: directory "/opt/data/tablespace1" exists but is not empty
Apr 29 18:32:43 slave01 patroni[30015]: 2018-04-29 18:32:43,658 ERROR: Error when fetching backup: pg_basebackup exited with code=1
Apr 29 18:32:43 slave01 patroni[30015]: 2018-04-29 18:32:43,658 ERROR: failed to bootstrap from leader 'master01'
Apr 29 18:32:43 slave01 patroni[30015]: 2018-04-29 18:32:43,658 INFO: Removing data directory: /opt/data/psql
Apr 29 18:32:48 slave01 patroni[30015]: 2018-04-29 18:32:48,300 INFO: Lock owner: master01; I am slave01
```
That last error then repeats every few minutes. The only recovery is to stop patroni, manually remove the PG_DATA directory and all tablespace directories and start patroni again. 

Is there any way to see more detailed messages about the error? I don't know if pg_basebackup sent any output to its stdout/stderr but I don't see a way to see that output since it's started by patroni.

Secondly, when patroni retries pg_basebackup, because we have tablespaces that exist, it seems to fail to remove those directories as they are not part of PG_DATA directory. Is this expected?

Depending on how the pg_basebackup failed, is it possible to restart it without losing all the replication progress? That's a rather unfortunate situation given that it can take days just to reach this point.

thanks!

**Comment by CyberDem0n** [comment]
Hi,

Actually your logs contain the reason why pg_basebackup has failed:
```
Apr 29 18:30:23 slave01 patroni[30015]: pg_basebackup: child process exited with error 1
```

`pg_basebackup: child process exited with error 1` -- this is the error message printed by pg_basebackup

By default Patroni starts pg_basebackup with `-X stream` arguments. pg_basebackup in this case spawns additional process which receives wal stream and writes it into pg_xlog directory.

For some unknown reason this subprocess exists earlier than expected (and with non zero exit code) what causes entire pg_basebackup to fail...

Patroni itself doesn't know anything about tablespaces and therefore can't clean them up before the next pg_basebackup attempt. Likely there it is possible to configure Patroni to use other methods to build relicas rather than default pg_basebackup: http://patroni.readthedocs.io/en/latest/replica_bootstrap.html#building-replicas

I would recommend you to wrap pg_basebackup into a shell script and inside this script clean up tablespaces before calling pg_basebackup. Also if you archiving wals it make sense to avoid streaming wals from pg_basebackup (don't specify -X stream).

Here you can also grab some ideas: https://github.com/zalando/spilo/blob/master/postgres-appliance/basebackup.sh

**Comment by CyberDem0n** [comment]
> For a failed pg_basebackup, is there any way at all to leverage some of the data that's already been copied?

Looks like you are talking about functionality similar to rsync. No, unfortunately pg_basebackup doesn't support it. It can only get everything from the master (or replica).
If you wrap pg_basebackup into a script and run it without streaming wals, then I hope it will become more stable.

Actually with the help of scripts you can even use rsync to build replicas, but this is a really slippery way and I would recommend to avoid it.

**Comment by seafoodbuffet** [comment]
> If you wrap pg_basebackup into a script and run it without streaming wals, then I hope it will become more stable.

You're suggesting something like the script that was referenced that manually starts pg_receivexlog/wal? Or to leverage some sort of WAL archiving with this? As of right now, I was hoping to rely on a streaming only solution, but perhaps that's not a great idea to begin with?

**Comment by CyberDem0n** [comment]
Patroni creates replication slots on the node where the replica wants to stream from (usually master). AFAIK, starting from 9.6 postgres will protect wals which were not consumed from replication slots from clean up, but unfortunately you are on 9.4.

If you don't have WAL archiving enabled, you can try to play with pg_receivexlog, but you have to stop it as soon as pg_basebackup is done. Also don't forget to move received wals into pg_xlog.

BTS, it's always good to have continuous archiving enabled, because people tend to do a lot of stupid things, like dropping all tables on production db :)

**Comment by seafoodbuffet** [comment]
Okay, thank you.
