### ISSUE TITLE
Suggestion to add explanation in the README regarding customization of /etc/postgresql-common/createcluster.conf

### ISSUE THREAD

**Issue by alago197** [zalando/patroni#676]
Hi,

I banged my head on the wall on this (had several FATAL: system id mismatch errors).  

I think it would be nice if the README of Patroni crearly states the order of installation of the PostgreSQL components , before performing the Patroni setup.  The postgresql-commons default of creating a clustered installation I think it would be useful to be mentioned, and advising to edit the /etc/postgresql-common createcluster.conf'"create_main_cluster" directive to false.

**Comment by alexeyklyukin** [comment]
Hi @alago197 

This problem is very Debian/Ubuntu specific. Patroni tries to be system and infrastructure agnostic, it is the task of the packager/docker image to prevent issues like the ones you have described.

Together with @CyberDem0n we have covered that and other commonly encountered issues in the Patroni trainings, for which there are slides published at https://speakerdeck.com/alexeyklyukin/managing-postgresql-clusters-with-patroni. Take a look at slide 100 and on.

I think the contents of those slides could be converted to a Troubleshooting page in the Patroni documentation and we certainly welcome pull-requests doing exactly that.

**Comment by alago197** [comment]
Worked like a charm. Bottom line is to start with a clean, controlled postgresql packages install, yes.
