### ISSUE TITLE
Once the cluster is started, how to configure a scheduled backup to GCS or S3 buckets?

### ISSUE THREAD

**Issue by gpernelle** [zalando/patroni#721]
Hi,
I have configured a cluster with the postgres-operator, but now i would like to configure a scheduled backup. How should I start to proceed? Is it something I can do by using 'patronictl edit-config'?

**Comment by CyberDem0n** [comment]
Backups are not really in the scope of Patroni.

postgres-operator deploys spilo docker image.
Inside an image there is Patroni, wal-e and cron, which is doing backups.
In addition to, postgres is archiving wals with the help of wal-e.

In order to get everything to work you have to provide the right environment values for spilo: https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst

Since you are using postgres-operator you should also read https://github.com/zalando-incubator/postgres-operator/blob/master/docs/reference/operator_parameters.md

**Comment by gpernelle** [comment]
thank you!

**Comment by osasidiaru** [comment]
True

**Comment by alexeyklyukin** [comment]
@gpernelle if you use the operator, then the modifications (i.e. S3 bucket) should be placed in the configuration of the operator itself, which also requires a subsequent restart of the operator itself.

**Comment by gpernelle** [comment]
Great, thanks a lot for your help!
