### ISSUE TITLE
Can you add support for pgpool II ?

### ISSUE THREAD

**Issue by twelfthdoctor** [zalando/patroni#766]
**Feature request**

[Stolon](https://github.com/sorintlab/stolon) has a built-in proxy server which allows me to proxy all my UPDATE, DELETE and INSERT queries to the master, and SELECT queries to slaves. Patroni doesn't have this useful feature.
Pgpool allows you to split read and write queries and proxy them to different nodes. So, I think that it`s good to add support of pgpool II (or your own proxy server) to Patroni.

**Why can't I simply use pgpool 2 ?**
I can't use pgpool II because of automatic failover. During automatic failover master's IP changes, but I still have IP of former master in my pgpool configuration, so pgpool sends **UPDATE** and **INSERT** queries to  the slave which has been a master before automatic failover. It causes errors. I don't want to update pgpool's configuration manually, so I decided to create a script which runs as a daemon and watching on **/db/postgres/leader** key in etcd key-value storage. Pgpool II configuration will be automatically updated when this key changes.

Here is a simple proof of concept:
```python
import etcd
import daemon
import parser
# daemon - https://pypi.org/project/python-daemon/
# etcd - https://pypi.org/project/etcd/ (I'm using an old etcd client here, you can rewrite it if you eant)

# Return list of IP addresses of all nodes in a cluster.
def get_members():
	client = etcd.Client(port=2379)
	members = client.read('/db/postgres/members')._children
	ips = []
	for member in members:
		url = member['value']['conn_url']
		ip = parser.parse("postgres://{}:5432/postgres", url)[0]
		ips = ips.append(ip)
	return ips

def get_master_name():
	client = etcd.Client(port=2379)
	master = client.wait('/db/postgres/leader').value
	return master

def write_pool(ips):
	# render pgpool config from a jinja2 template
	template = jinja2.Template(''' load_balance_mode = on
	master_slave_mode = on
	master_slave_sub_mode = 'stream'
    {% for  num, ip in ips %}
    backend_hostname{{num}} = '{{ip}}'
    backend_port{{num}} = 5432
    backend_weight{{num}} = 1
    backend_data_directory{{num}} = '/data/patroni'
    backend_flag{{num}} = 'ALLOW_TO_FAILOVER'
    {% endfor %}
	''')
	content = template.render(ips=ips)
	# write file
	with open('/etc/pgpool.conf', 'w+') as file:
		file.write(content)

def update_pool():
	# wait until master changed
	master = get_master_name()
	# get members of cluster
	members = enumerate(get_members())
	# rewrite pool
	write_pool(members)	

def run():
	# Daemonize our script
	with daemon.DaemonContext():
		update_pool()

run()		
```

**Comment by CyberDem0n** [comment]
> Stolon has a built-in proxy server which allows me to proxy all my UPDATE, DELETE and INSERT queries to the master, and SELECT queries to slaves. 

AFAIK it can't work as LAYER 7 proxy.

> Patroni doesn't have this useful feature.

You can configure HAProxy to load-balance read-only traffic across available replicas: https://github.com/zalando/patroni/blob/master/extras/confd/templates/haproxy.tmpl#L26-L32
Off course it will require you to have two connection urls in the application.

> Pgpool allows you to split read and write queries and proxy them to different nodes. 

Unfortunately it is not very reliable, because SELECT statements are able to modify data if they call VOLATILE functions.

> Here is a simple proof of concept:

I would suggest to use [confd](https://github.com/kelseyhightower/confd) for that. Its main goal to generate configuration files from templates and keep them in sync with information from DCS.  It already supports etcd, consul and zookeeper.

We already have an example of generating HAProxy configuration with the help of confd: https://github.com/zalando/patroni/tree/master/extras/confd
And [here](https://github.com/zalando/patroni/blob/master/docker/entrypoint.sh#L34-L45) is an example how to start confd.

**Comment by twelfthdoctor** [comment]
OK, I can run my script via on_role_change section in patroni's YAML configuration.

**Comment by CyberDem0n** [comment]
@twelfthdoctor it is better to delegate this task to confd.
It periodically checks the state in DCS and updates config if necessary updates config and reloads service.

**Comment by jberkus** [comment]
Closing this, as there are no plans to add built-in pgpool support.

**Comment by cobolbaby** [comment]
Confd template for pgpool: https://github.com/cobolbaby/dockerize-and-ansible/blob/master/pgpool/config/confd/templates/pgpool.tmpl
