### ISSUE TITLE
why are we parsing URIs?

### ISSUE THREAD

**Issue by jberkus** [zalando/patroni#78]
The connection strings to members of the cluster are in the form of URIs.  For PostgreSQL 9.2 and later, URIs are supported by psycopg2 as connection strings, and are supported by various PostgreSQL utilities.  Yet for some reason, the Patroni code spends a lot of time parsing and recomposing URIs instead of just using them.  Why?

This relates to issue #61.

**Comment by CyberDem0n** [comment]
It does it in a few cases:
1) When establishing connection to the own postgresql instance.
2) When executing sync_from_leader or pg_rewind
3) When checking content of recovery.conf (primary_conninfo)

1 and 2 are not a problem at all, because they are executed not so often.

3 is executed every 10 seconds. For me it also does not look like a real problem and I don't think that we should optimize it...


As I could see you a referring issue #61
Well, for opening a local connection we could avoid building connection URL and then parsing it.
The only reason to do it was unifying code which is adding some options, i.e.:
          'fallback_application_name': 'Patroni',                                                                     
          'connect_timeout': 3,
          'options': '-c statement_timeout=2000',

**Comment by jberkus** [comment]
I'm not concerned about execution time; I'm concerned about unmaintainability and unreadability of the code.  As far as I can tell, we repeatedly parse connection URLs into a dictionary, then reassemble them as a space-delimited connection string, which is all completely unnecessary.

Since I'm going to overhaul how we manage connection information anyway, it seems like we should just stick to storing everything as a url, and using it as a url.

**Comment by jberkus** [comment]
Now part of issue #85.  Closing to fold into that issue.
