### ISSUE TITLE
patroni not starting in slave 

### ISSUE THREAD

**Issue by SubhaParasuraman** [zalando/patroni#796]
Hi all,
I am really a very newbie to patroni and stuff.So please bear if any query is so simple enough.I have 2 servers
172.16.251.25 --master
172.16.251.27 --slave .I have installed etcd and patroni on both the servers .I have installed etcd -2.0.9 version via rpm  and edited the etcd.conf file and started etcd on both the servers.Sometimes etcd stops in slave server .and cluster health shows unhealthy  and also checking member list in the master name and clientURL is not updated.
[root@s2n etcd]# etcdctl member list
2067e570df39ae8a: name=pg0 peerURLs=http://172.16.251.25:2380 clientURLs=http://172.16.251.25:2379
e27f59d4e2dd4c9e: name= peerURLs=http://172.16.251.27:2380 clientURLs= 

The configuration of etcd and patroni yaml files and status of etcd,patroni is also 
[masteryaml.txt](https://github.com/zalando/patroni/files/2327549/masteryaml.txt)
[slaveyaml.txt](https://github.com/zalando/patroni/files/2327550/slaveyaml.txt)
[patroninow.docx](https://github.com/zalando/patroni/files/2327557/patroninow.docx)

attached Please let me know anything I have configured wrongly.Any other logs needed let me know.I wish someone could help me on it.

**Comment by CyberDem0n** [comment]
First of all  - you need to have 3 etcd nodes for HA.
And the second - this is not the right place to ask questions about etcd

**Comment by alexeyklyukin** [comment]
It looks like you have misconfigured your Etcd, and therefore, Patroni cannot proceed.

See the page at
https://coreos.com/etcd/docs/latest/v2/clustering.html
as an example on how to configure Etcd with a static list of members.

If you need to add a new member to the cluster, the process is really 2-step. See 
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member

From the examination of your logs it seems the primary issue is that you haven't cleaned up your previous etcd installation before starting the new one (the first node being started `2067e570df39ae8a`  tries to send requests to another node `e27f59d4e2dd4c9e` ). 
```
Aug 28 01:27:29 s2n etcd[11349]: 2018/08/28 01:27:29 raft: 2067e570df39ae8a [logterm: 2, index: 912198] sent vote request to e27f59d4e2dd4c9e at term 20019
Aug 28 01:27:29 s2n etcd[11349]: 2018/08/28 01:27:29 etcdserver: publish error: etcdserver: request timed out
```

There are other potential issues as well (advertising localhost, not following the proper procedure when adding a node), please, look at the links above and try to follow them.

It is crucial to understand how Etcd works before relying on it. You may want to look at how RAFT (the algorithm behind Etcd distributed consensus decision making) works, i.e. look at the official docs: https://coreos.com/etcd/

A working etcd (as confirmed by `etcdctl cluster-health` and `etcdctl member-list` is a pre-requisite for running Patroni. Without it, Patroni will fail immediately after trying to connect to Etcd, as demonstrated in your logs.

Last, but not least, running your Etcd cluster with 2 nodes is ok for the test environment, but never do it in production, since there is no resiliency in this setup. Etcd requires a majority of nodes to continue  to continue accepting writes, and the majority of 2 is 2. Consider running at least 3 nodes on 3 different servers (running Etcd and PostgreSQL on the same server is also not recommended), that way you can loose one Etcd node and still keep your cluster running.

As a sidenote, posting your logs in docx might make them unreadable to some people. Consider always using plain-text format for the logs and output you share with others.

**Comment by SubhaParasuraman** [comment]
Thanks a lot for a clear explanation.I shall try to reconfigure and let know in case of any issues.
