### ISSUE TITLE
Add after_failover callback action

### ISSUE THREAD

**Issue by psuderevsky** [zalando/patroni#825]
After failover some WAL records can be lost and absent in WAL archive so PITR with previous base (full) backup would be impossible to after-failover point.  Action **on_role_change** is usefull for automation of new base backup creation, but this action can cause unwanted aftereffects. For example postgres demotion after _retry_timeout_ would also trigger **on_role_change** action, but if no actual failover occures and node returns as a master callback script still will cause new base backup creation and => unnecessary load.
Callback action  **after_failover** that will be triggered only if failover had been actually performed can improve this logic.

**Comment by CyberDem0n** [comment]
Can you elaborate more on `after_failover`? How it should work? When should it be called?

Actually I think you can get desired behavior with `on_role_change`, because like any other callback it receives a set of arguments: `callback_name`, the new `role` and `scope`.
You can simply check that `role=master`

**Comment by alexeyklyukin** [comment]
I think the issue here is to distinguish between the cases where the master just demoted and then promoted itself back and those that involved promotion from another member.

Perhaps there is a path to another feature of showing the list of member names serving as masters together with the timeline history in Patroni. If we had this data, we could also provide a "previous_leader_name" to the on_role_change callback instead of inventing a completely different one. The callback could use this data to act differently on the cases where the previous and current leader names are different.

**Comment by bradnicholson** [comment]
I'm not sure a blind `on_failover` hook would be best here anyway to solve this case.  

You would want, on promotion to be able to run a script to detect if you have a hole in your archive timeline, and only trigger a new backup if that is the case, and this is often not the case.  Whether you do will depend on your write load and  `archive_timeout` setting.
