### ISSUE TITLE
Confusing Errors When REST URL set same port on localhost

### ISSUE THREAD

**Issue by dtseiler** [zalando/patroni#832]
I was troubleshooting a problem where `patronictl switchover` or `patronictl failover` were failing with this error:

```
-bash-4.2$ patronictl -c /etc/patroni/patroni.yml switchover
Master [pg0]:
Candidate ['pg1', 'pg2'] []: pg1
When should the switchover take place (e.g. 2015-10-01T14:30)  [now]:
Current cluster topology
+---------+--------+----------------+--------+---------+-----------+
| Cluster | Member |      Host      |  Role  |  State  | Lag in MB |
+---------+--------+----------------+--------+---------+-----------+
| foo     |  pg0   | 192.168.205.11 | Leader | running |       0.0 |
| foo     |  pg1   | 192.168.205.12 |        | running |       0.0 |
| foo     |  pg2   | 192.168.205.13 |        | running |       0.0 |
+---------+--------+----------------+--------+---------+-----------+
Are you sure you want to switchover cluster foo, demoting current master pg0? [y/N]: y
Switchover failed, details: 503, Switchover failed
```

Looking at the logs on pg0 (primary), we see these messages:
```
Oct 18 20:26:04 patroni1 patroni[6213]: 2018-10-18 20:26:04,795 INFO: Got response from pg1 http://127.0.0.1:8009/patroni: {"database_system_identifier": "6613772782514452569", "postmaster_start_time": "2018-10-18 18:56:14.896 UTC", "timeline": 1, "xlog": {"location": 184691720}, "patroni": {"scope": "foo", "version": "1.4.4"}, "replication": [{"sync_state": "async", "sync_priority": 0, "client_addr": "192.168.205.12", "state": "streaming", "application_name": "pg1", "usename": "replicator"}, {"sync_state": "async", "sync_priority": 0, "client_addr": "192.168.205.13", "state": "streaming", "application_name": "pg2", "usename": "replicator"}], "state": "running", "role": "master", "server_version": 100005}
Oct 18 20:26:04 patroni1 patroni[6213]: 2018-10-18 20:26:04,892 INFO: Member pg1 exceeds maximum replication lag
Oct 18 20:26:04 patroni1 patroni[6213]: 2018-10-18 20:26:04,892 WARNING: manual failover: no healthy members found, failover is not possible
Oct 18 20:26:04 patroni1 patroni[6213]: 2018-10-18 20:26:04,892 INFO: Cleaning up failover key
```

However there is no lag whatsoever. The problem was due to the configuration having the URL of `127.0.0.1:8009` for `restapi.connect_address` on all 3 nodes in the cluster. When the primary gets this URL from the DCS to try to talk to patroni on the target replica, it ends up talking to itself (but thinking it is talking to the replica). It sees `"role": "master"`, which triggers this set of events:

1. in https://github.com/zalando/patroni/blob/master/patroni/ha.py#L36, `wal` is set to `False` because `not is_master` fails. Also no `received_location` or `replayed_location` value is returned from a master node.
2. that gets passed up the chain from `fetch_node_status()` to `fetch_nodes_statuses()` to `is_failover_possible()`
3. That calls `is_lagging` which will fails, emitting the "maximum replication lag" error.

We should look at the following possible solutions:

- Check the `restapi.connect_address` values to make sure they are unique (address and port) during bootstrap, which is when this value is loaded into the DCS.
- If the REST call to a replica returns that it is a master, something is wrong and we should error with a different message, certainly not a lag error. Perhaps something suggesting a configuration error.

**Comment by CyberDem0n** [comment]
Hi @dtseiler 

it is actually the hard topic.

From one side you want to know that the node is returning the false results on REST API call (because you are calling the wrong url) and apparently when we call the replica you expect that it won't report itself as a master. Unfortunately the real world is a little bit more complicated and there are a lot of race conditions, for example the node could be unexpectedly promoted and start reporting itself as a master and it doesn't necessarily means that it is wrong. Indeed, in this case we can definitely improve error reporting and should postpone/abort failover/switchover.

Regarding uniqueness of restapi.connect_address: it is not enough to require it, the connect_address should also be accessible from the ALL nodes in the cluster. I think in this case we should improve the documentation and implicitly tell about that.
