### ISSUE TITLE
Is there support for priority of master node?

### ISSUE THREAD

**Issue by patsevanton** [zalando/patroni#852]
Hello!
I have 2 hardware server for PostgreSQL replication.
I know that patroni dont support install for 2-node cluster.
If i create 3-th node of virtual Is there support for priority of master node? (for set master only hardware node)

**Comment by ants** [comment]
There is no limitation on the number of Patroni nodes in a cluster. You can use 3, 2 or even 1 if you like. 

The limitation is with DCS used to agree on cluster state (e.g. etcd). It's fundamentally impossible to make a failure tolerant DCS with less than 3 separate nodes. If the nodes share any hardware that hardware will become a single point of failure. Running 2 etcd nodes on the same physical server will make cluster lose quorum if that server fails. Running 2 etcd nodes on the same power circuit will make the cluster lose quorum if that power circuit fails, and so on.

**Comment by patsevanton** [comment]
I know that failure tolerant DCS with less than 3 separate nodes.

My question not about etcd!
I want master postgesql should be on hardware server. For example, 1 - hardware, 2 - hardware, 3 - vmware. Master only 1 or 2 node.

**Comment by ants** [comment]
Set nofailover tag to true on the node that should not become a master.

**Comment by ibotty** [comment]
AFAICT the question is not on how to prevent a node to become leader, but to give priority to the node that has a physical disk (and no remote storage).  That is, when the one specific node fails it should failover to one of the other nodes.

**Comment by dberardo** [comment]
i think your comment @ants  is just a workaround, but does not fully meet the desired behavior.

the question is, is it possible to assign weight / priority in etcd/patroni on nodes during election?

mongodb has this feature: https://docs.mongodb.com/manual/tutorial/adjust-replica-set-member-priority/

that would be indeed very valuable to have, since it would reduce significantly hardware costs (one could aim to have only one node with high CPU resources, hoping that this one will besome leader most of the time, while using other nodes only during failover / maintenance times.

**Comment by mathisve** [comment]
100% agree with @dberardo, would love to see this feature!
