### ISSUE TITLE
Recovering from  DCS downtime: reduce flapping

### ISSUE THREAD

**Issue by redbaron** [zalando/patroni#909]
If Kubernetes APIServer (or any DCS for that matter)  goes down for longer than leader lock TTL, once it comes back up all candidates rush to acquire lock, which can cause leader switch even though old leader is perfectly fine and healthy.

I think chance of unnecessary leader switch can be reduced if node which was a former reader attempts to re-acquire lock more frequently than former followers by making leader's `run_cycle` twice as fast than everyone's else.

More sophisticated approach would be to recognize DCS downtime and run separate cycle waiting for DCS to be up and make follower's attempts to acquire lock  much less frequent than folllower's. How much? Probably 2x normal cycle time to detect DCS downtime.

I am happy to make a PR if idea looks good to you and we can agree on a best approach to implement it in the code.

**Comment by CyberDem0n** [comment]
Hi,

all important calls to DCS are done with retry_timeout, which is 10s by default.
K8s API server is not an exception, if it is not accessible, Patroni will repeat HTTP calls until the call actually succeeds or retry_timeout is reached. After that, the next HA loop is scheduled immediately.

**Comment by redbaron** [comment]
> After that, the next HA loop is scheduled immediately.

yes and thats source of flapping.  If Patroni  special cased DCS unavailability , then it guarantee recover to the previously known leader and no unnecessary switchover would happen.

**Comment by CyberDem0n** [comment]
I think you are missing some points in the HA workflow.

If DCS is unavailable, Patroni STOPS postgres running as master, creates recovery.conf and brings it back as read-only. When DCS becomes again available, promote will happen anyway (postgres will create the new timeline) and we don't really care on which node.

> all candidates rush to acquire lock

Nope, first they will connect to each other in order to determine which member has the biggest WAL location.

> More sophisticated approach would be to recognize DCS downtime and run separate cycle waiting for DCS to be up

This is a very typical mistake. We are living in a distributed world. From the Patroni perspective, we can't distinguish between DCS is not available and being PARTITIONED, therefore shutting down the postgres and starting it as read-only is the only possible option.

**Comment by redbaron** [comment]
> I think you are missing some points in the HA workflow.

yes I am

>  From the Patroni perspective, we can't distinguish between DCS is not available and being PARTITIONED, therefore shutting down the postgres and starting it as read-only is the only possible option.

I see, you do self-fencing by switching Posgres into read-only mode. This is means that service availability depends on K8S APIServer being up, which wasn't the case before introducing patroni: K8S control plan could all go down, but  all containers, routes and iptables rules stay up and service  is not impacted. It is especially troublesome since APIServer is fiddled with quite more than just "deploy and forget" etcd setup, so probably we'll use that one.

Thanks for clarification.

**Comment by Jan-M** [comment]
We had similar discussions internally, when it came to SLAs of the API server and how this impacts us down stream. As we kind of could not be better than the API. I am not sure we ever reached consensus but turns out the API server that is managed by another team is doing well and the rolling upgrades their do not impact our uptime. Bigger impact is worker node upgrades and frequent auto scaling.

In the end we did favor not being responsible for another component, we wanted to manager Postgres at scale and not ETCD deployments. And sharing ETCD with K8S API server due to authorization was and is not an option.
