### ISSUE TITLE
Kubernetes DCS: use namespaced annotation for status

### ISSUE THREAD

**Issue by redbaron** [zalando/patroni#938]
When configured with Kubernetes DCS, it uses `status` annotation on each pod, which can conflict with other users. This annotation should be namespaced (such as `patroni.zalan.do/status`) or at least be configurable

**Comment by CyberDem0n** [comment]
I just looked closer on this issue and it seems that it would be a breaking change.
The `status` annotation is used by every Patroni cluster member as a discovery mechanism.
If all replicas will start writing such data under the new name, the current primary will no be able to read it, what will break the switchover mechanism, because the primary needs to connect to the potential candidates via API in order to figure out that they are in a good shape before shutting down and releasing leader lock.
