### ISSUE TITLE
consul: register ttl check instead http check

### ISSUE THREAD

**Issue by combrs** [zalando/patroni#957]
Now, when 'register_service' is used in configuration for consul, there is a HTTP health check are registered.
When 'service_check_interval' are not set, default interval is  unknown.
But in doc there is a sentence : "Additional checks, in particular the “serfHealth”, may cause the leader lock to expire faster than in ttl seconds when the leader instance becomes unavailable".
Instead to try to bind service_check_interval in config with ttl value in DCS by hand, maybe better register TTL health check instead HTTP check?

As described [here](https://www.consul.io/docs/agent/checks.html#TTL) the check may be registered with known 'ttl' value. 
It may remove some uncertainty and doubt about interval, timeout of HTTP health check as registered now.

But after register a TTL health check it need to update it from application (not only a leader key).
"a healthy app can periodically PUT a status update to the HTTP endpoint; if the app fails, the TTL will expire and the health check enters a critical state".

**Comment by CyberDem0n** [comment]
I think you are mixing two different components here.
1. The sentence `"Additional checks, in particular the “serfHealth”, may cause the leader lock to expire faster than in ttl seconds when the leader instance becomes unavailable"` has nothing to do with consul services. It applies only to the session which is created by every member and later used for creating member and leader keys. This session is already periodically renewed, on every cycle of HA loop.
2. HTTP health check applies only to the services and works pretty much the same way as health checks in HAProxy.

**Comment by combrs** [comment]
Ok, I got it (difference between service health and kv session existence). But it need clarification in doc, maybe.
1. How serfHealth does affect on ttl for leader key in kv store? If some consul instance becomes unavailable and serfHealth become unhealthy, and leader key are in lock session from unhealthy agent, that key are deleted immediately and not in it's own ttl ?

2. What are default service_check interval for HTTP service check?  "HTTP ... checks must include an interval field", but it is unknown . If service health check become unhealthy, only service is unavailable via DNS query, but it does not affect other patroni work ? as shown [here](https://learn.hashicorp.com/consul/getting-started/checks#checking-health-status)
(I found it in log: when service registering it show its parameters, and "'interval': '5s'"  among it. But it shown once in log and go to history fast)
3. somewhere I saw recommendation about this parameter:
````
consul:
  checks: []
````
but when I try to appy it, I can not see any changes.  Service check with it registered too.

(Patroni users are not, maybe, consul or other DCS experts and some clarification in docs may be useful)

**Comment by CyberDem0n** [comment]
> How serfHealth does affect on ttl for leader key in kv store? 
Somewhere I saw recommendation about this parameter consul.checks: [], but when I try to appy it, I can not see any changes. 

In case if local consul agent is isolated from the consul cluster (or maybe consul agent is restarted), `serfHealth` will immediately invalidate all sessions associated with this specific agent. Any keys in the KV created with such sessions would be removed. This is especially bad for the `/leader` lock. When you set `consul.checks` to `[]`, it will not invalidate sessions due to serfHeath fail but when TTL is reached. You can read more about this problem [here](https://github.com/zalando/patroni/issues/522)

> What are default service_check interval for HTTP service check? "HTTP ... checks must include an interval field", but it is unknown . If service health check become unhealthy, only service is unavailable via DNS query, but it does not affect other patroni work ? as shown here
(I found it in log: when service registering it show its parameters, and "'interval': '5s'" among it. But it shown once in log and go to history fast)

You are still missing how consul services work.
service_check_interval is set by default to 5s https://github.com/zalando/patroni/pull/802/files#diff-01f2f2d2bffe1407b2928d1a79e456b0R209
Master registers itself with `tags=['master']` and health-check url `http://$restapi.connect_address/master`
Replica register itself with `tags=['replica']` and health-check url `http://$restapi.connect_address/replica`

In case is health-check url doesn't return http status code 200, the given host:port disappers from the consul DNS.

Consul is using such health-checks absolutely the same way as for example [haproxy](https://github.com/zalando/patroni/blob/master/extras/confd/templates/haproxy.tmpl#L19-L32)



> But it need clarification in doc, maybe.

Feel free to contribute it.
