### ISSUE TITLE
remove_data_directory_on_diverged_timelines

### ISSUE THREAD

**Issue by IJOL** [zalando/patroni#978]
Hola:

I've set remove_data_directory_on_diverged_timelines to true, using edit-config it seems correctly done, stop ther replica, wait for some time, and restarted it i get messages in the replica log about not being able to get the segment where it ws when paused, i've expected that setyting that option, replica should reinit itself given the stater, but nothing happeed,m it's obvius i'm overlooking something, or didnt understand how to use it, anyway i've trie to search the param in my old 1.34 ltes version and nothing found....

**Comment by CyberDem0n** [comment]
In order to deal with such issues you have to configure [continuous archiving](https://www.postgresql.org/docs/current/continuous-archiving.html)

**Comment by IJOL** [comment]
Maybe wal archiving is an overshoot for my app and needs, simplly having some replicas without any lag will do for me, so i'm trying to see if any replica starts to lag, and if lag dont dissapear in some time, simply reinit that replic,. is this use case doable with patroni as it is now?, if not i'll try to scratch 
that itch myself, any guidance where to put it in the more fashionable way for the codebase, wil be appreciatted..

Thanks anyway

**Comment by CyberDem0n** [comment]
> Maybe wal archiving is an overshoot for my app and needs

It is up to you, but in general, it is always useful. Automatic failover won't help to recover an accidentally dropped table.

When the replica node isn't running Patroni is removing the replication slot, therefore master starts recycling wal segments.
Starting from 1.5.1 there is a workaround exists, one can use permanent replication slots feature in order to avoid recycling of wal segments by the master:
```yaml
$ patronictl edit-config

slots:
  node1:
    type: physical
  node2:
    type: physical
  node3:
    type: physical
```

node1, node2, and node3 are names of cluster members.

If the node2 for example leaves the cluster, Patroni will still keep the replication slot for it and postgres on master will not remove WALs because nobody is streaming from this slot.

There is one minor issue though, Patoni itself won't filter out the master node from this list, so you have to update the configuration after every failover/switchover, but it is easily scriptable with the help of callbacks mechanism.

**Comment by IJOL** [comment]
Ok,  I understand, but there is another big problem forme, node names in docker are no easily predictables nor easily recorded and written, i dso run al my patroni ( great succes i must say ) from inside a swarm,  the need to edit-config every so often, it's at least cumbersome... it wopuld much easier to simply dont permit the lag to grow over a given size, and if so simply reinit replica, my db is big but not very very big, so doint it that way, is very workable... if i've got and event on that i could attache some code to it

**Comment by CyberDem0n** [comment]
> it would much easier to simply don't permit the lag to grow over a given size, and if so simply reinit replica

This is more like a task for some external operator. Patroni already provides REST API for the that.

Just by itself Patroni isn't able to figure out the reason why replica is lagging behind.
It might be some bad configuration and long-running queries. It also could be the missing WAL on the primary. The last one is possible to detect only from the postgres logs and it is not really a Patroni task to parse postgres logs.
