### ISSUE TITLE
PATRONI_POSTGRESQL_CONFIG_DIR variable does not change default config directory

### ISSUE THREAD

**Issue by kakhaUrigashvili** [zalando/patroni#983]
I am trying to change the config directory, but it does not work.
Here is a part of my docker-compose file:
.....
patroni_db4:
    container_name: patroni_db4
    image: patroni/postgres:10
    hostname: patroni_db4
    links:
      - patroni_etcd:patroni_etcd
    env_file: localhost.env
    environment:
      PATRONI_ETCD_URL: http://patroni_etcd:2379
      PATRONI_NAME: patroni_db4
      PATRONI_SCOPE: testcluster
      PATRONI_POSTGRESQL_CONFIG_DIR: /tmp # config file are still in /data/testcluster directory
      PATRONI_LOG_LEVEL: DEBUG

Same behaviour is observed for PATRONI_POSTGRESQL_DATA_DIR

https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html

**Comment by CyberDem0n** [comment]
Custom config dir via environment is clearly broken, I missed this fact when reviewing https://github.com/zalando/patroni/pull/466
The fix is very simple, the `'config_dir'` should be just added [here](https://github.com/zalando/patroni/blob/master/patroni/config.py#L236).

data_dir is a different topic, it is just "hardcoded" [here](https://github.com/zalando/patroni/blob/master/docker/entrypoint.sh#L90)

BTW, this docker image is made for test purposes.

**Comment by kakhaUrigashvili** [comment]
@CyberDem0n 
I added 'config_dir' as you suggested. It does create config files in the right directory now.
The bootstraping of new cluster seems to be broken now.
patroni_db3     | 2019-02-25 18:34:23,118 ERROR: Exception during execution of long running task bootstrap
patroni_db3     | Traceback (most recent call last):
patroni_db3     |   File "/patroni/async_executor.py", line 97, in run
patroni_db3     |     wakeup = func(*args) if args else func()
patroni_db3     |   File "/patroni/postgresql.py", line 1681, in bootstrap
patroni_db3     |     and self._configure_server_parameters() and self.start()
patroni_db3     |   File "/patroni/postgresql.py", line 899, in start
patroni_db3     |     self._write_postgresql_conf(configuration)
patroni_db3     |   File "/patroni/postgresql.py", line 1112, in _write_postgresql_conf
patroni_db3     |     os.rename(self._postgresql_conf, self._postgresql_base_conf)
patroni_db3     | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/postgresql.conf' -> '/tmp/postgresql.base.conf'

What docker image should I use for non-testing purposes? I was not able to find an official image on DockerHub, so I am building it myself.

**Comment by CyberDem0n** [comment]
Well, the `config_dir` was mainly implemented for compatibility with debian/redhat, because they prefer to keep config files in the separate directory.
That doesn't make much sense if you are in the docker and actually I've never tried to use it myself.

Regarding the official image: Patroni is platform independent and docker is not required to run it.
For docker-based deployments (manly on k8s) we use [Spilo](https://github.com/zalando/spilo), it contains Patroni, all supported postgres versions, a lot of postgres extensions and some additional tooling like wal-e/wal-g/pgbouncer.

**Comment by kakhaUrigashvili** [comment]
@CyberDem0n I will look into Spilo. We can close this ticket.
